import { Category, Product, CategoryInfo, BlogPost, Order, Voucher } from './types';

export const CATEGORY_METADATA: CategoryInfo[] = [
  { 
    name: 'Áo thun nam', 
    slug: 'ao-thun-nam', 
    icon: '/images/ao-thun-nam.webp' 
  },
  { 
    name: 'Áo thun thể thao nam', 
    slug: 'ao-thun-the-thao-nam', 
    icon: '/images/ao-thun-the-thao-nam.webp' 
  },
  { 
    name: 'Áo polo nam', 
    slug: 'ao-polo-nam', 
    icon: '/images/ao-polo-nam.webp' 
  },
  { 
    name: 'Quần thể thao nam', 
    slug: 'quan-the-thao-nam', 
    icon: '/images/quan-the-thao-nam.webp' 
  },
  { 
    name: 'Phụ kiện thể thao', 
    slug: 'phu-kien-the-thao', 
    icon: '/images/phu-kien-the-thao.webp' 
  },
];

export const CATEGORIES: Category[] = CATEGORY_METADATA.map(c => c.name);

export const PRODUCTS: Product[] = [
  {
    id: `1f4a58a8-7a60-4b8a-860b-17d8607e7167`,
    productCode: `UR-1F4A58A8`,
    slug: `ao-thun-nam-ur-bee-premium-cotton`,
    name: `Áo Thun Nam UR BEE Premium Cotton`,
    description: `<p><strong>Áo Thun Nam UR BEE Premium Cotton</strong> là lựa chọn dành cho nam giới muốn có một mẫu áo dễ mặc, gọn form và đủ chỉn chu cho nhiều hoàn cảnh. Sản phẩm tập trung vào cảm giác mặc thực tế: chất liệu premium cotton, form regular fit, màu Đen, Trắng, Xanh đen và bảng size rõ ràng để người mua chọn nhanh hơn.</p><h2>Điểm nổi bật của áo thể thao nam premium cotton</h2><p>Khi chọn <a href="/ao-thun-nam/the-thao">áo thun thể thao nam</a>, khách hàng thường quan tâm nhất đến độ thoải mái, độ bền form và khả năng phối đồ. Áo Thun Nam UR BEE Premium Cotton được định vị theo hướng basic premium: không cầu kỳ, không quá phô trương, nhưng vẫn tạo cảm giác sạch, khỏe và nam tính.</p><ul><li><strong>Chất liệu:</strong> premium cotton cho cảm giác mềm và dễ chịu khi mặc lâu.</li><li><strong>Form:</strong> regular fit giúp tổng thể gọn hơn nhưng vẫn đủ khoảng thở khi vận động.</li><li><strong>Màu sắc:</strong> Đen, Trắng, Xanh đen phù hợp nhiều kiểu quần và giày.</li><li><strong>Size:</strong> M, L, XL, XXL, 3XL, 4XL giúp khách dễ chọn theo vóc dáng.</li></ul><h2>Chất liệu và cảm giác mặc</h2><p>Với chất liệu premium cotton, sản phẩm hướng đến cảm giác mặc ổn định trong nhịp sống hằng ngày. Nội dung sản phẩm không bịa thêm thông số kỹ thuật ngoài dữ liệu đầu vào, nhưng vẫn mô tả rõ giá trị mà khách hàng có thể cảm nhận: bề mặt vải dễ chịu, dễ phối và phù hợp phong cách thể thao nam hiện đại.</p><p>Nếu bạn đang xây dựng tủ đồ nam cơ bản, một mẫu áo có chất liệu tốt sẽ giúp giảm cảm giác phải thay đổi trang phục quá nhiều trong ngày. Áo có thể đi cùng jeans, jogger hoặc <a href="/quan-the-thao-nam">quần thể thao nam</a> để tạo set đồ gọn, năng động.</p><h2>Form dáng và phong cách phối đồ</h2><p>Form regular fit phù hợp người thích sự cân bằng giữa thoải mái và chỉn chu. Khi mặc đi làm môi trường thoải mái, đi cà phê, du lịch ngắn ngày hoặc tập luyện nhẹ, sản phẩm vẫn giữ được vẻ đơn giản, dễ gần và không bị quá xuề xòa.</p><p>Với màu Đen, Trắng, Xanh đen, bạn có thể phối theo 3 hướng: tối giản với quần đen, năng động với quần thể thao, hoặc casual với quần jeans. Cách phối này giúp sản phẩm có tính ứng dụng cao hơn thay vì chỉ dùng cho một bối cảnh.</p><h2>Ai nên chọn mẫu áo này?</h2><p>Áo Thun Nam UR BEE Premium Cotton phù hợp với người mua ưu tiên sự rõ ràng: biết mình cần chất liệu gì, form gì, màu gì và mức giá bao nhiêu. Đây là nhóm khách không muốn đọc lời quảng cáo quá đà, mà cần mô tả sản phẩm đủ cụ thể để ra quyết định nhanh. Vì vậy nội dung sản phẩm nên nói thẳng vào trải nghiệm mặc, khả năng phối đồ và cách chọn size.</p><p>Nếu khách hàng đang tìm một mẫu áo để mặc thường xuyên, đi chơi cuối tuần hoặc phối với outfit thể thao nhẹ, sản phẩm có lợi thế ở tính dễ dùng. Nếu khách cần một mẫu chuyên dụng cho vận động cường độ cao, trang sản phẩm nên bổ sung thêm dữ liệu thật về độ co giãn, độ thoáng hoặc ảnh test thực tế trước khi khẳng định sâu hơn.</p><h2>Checklist trước khi đặt mua</h2><ul><li>Kiểm tra đúng màu muốn mua: Đen, Trắng, Xanh đen.</li><li>Đối chiếu size M, L, XL, XXL, 3XL, 4XL với số đo cá nhân.</li><li>Xem ảnh mặt trước, ảnh chi tiết chất liệu và ảnh mặc thật nếu shop đã bổ sung.</li><li>Đọc kỹ phần chất liệu premium cotton và form regular fit để tránh chọn sai kỳ vọng.</li></ul><p>Checklist này giúp khách hàng tự tin hơn trước khi thêm sản phẩm vào giỏ. Với ecommerce thời trang, mô tả tốt không chỉ để lên SEO mà còn phải giảm câu hỏi lặp lại về size, màu và cảm giác mặc.</p><h2>Gợi ý ảnh nên bổ sung cho sản phẩm</h2><p>Để trang sản phẩm mạnh hơn, nên có ít nhất 3 nhóm ảnh: ảnh chính rõ toàn bộ áo, ảnh cận chất liệu/đường may và ảnh mặc thật trên người mẫu nam. Nếu có đủ ảnh, hệ thống Image SEO sẽ tạo fileName, alt, title và caption riêng cho từng ảnh để hỗ trợ Google hiểu đúng sản phẩm.</p><p>Ảnh chính nên sạch nền, không che sản phẩm và không dùng chữ quá lớn trên ảnh. Ảnh lifestyle nên thể hiện cách phối thật với quần và giày để người mua hình dung sản phẩm trong đời sống hằng ngày.</p><h2>Hướng dẫn chọn size</h2><p>Các size hiện có gồm <strong>M, L, XL, XXL, 3XL, 4XL</strong>. Khi chọn size, hãy ưu tiên số đo vai và vòng ngực trước, sau đó mới cân nhắc thói quen mặc ôm hay rộng. Người thích vận động hoặc muốn thoải mái cả ngày có thể chọn size tạo dư nhẹ ở vai và ngực.</p><p>Để chọn chính xác hơn, bạn có thể tham khảo <a href="/blog/ao-thun-tap-gym-nen-chon-loai-nao">cách chọn áo thun tập gym</a>. Nếu số đo nằm giữa hai size, lựa chọn an toàn thường là size lớn hơn, đặc biệt khi bạn thích mặc thoáng hoặc phối layer.</p><h2>Cách chăm sóc để áo bền đẹp</h2><ul><li>Giặt ở chế độ nhẹ, tránh ngâm quá lâu với chất tẩy mạnh.</li><li>Lộn trái áo trước khi giặt để giảm ma sát bề mặt.</li><li>Phơi nơi thoáng, hạn chế nắng gắt trực tiếp trong thời gian dài.</li><li>Ủi ở nhiệt độ phù hợp với chất liệu vải.</li></ul><h2>Câu hỏi thường gặp</h2><h3>Áo Thun Nam UR BEE Premium Cotton phù hợp mặc khi nào?</h3><p>Sản phẩm phù hợp mặc hằng ngày, đi chơi, di chuyển nhẹ và phối cùng quần thể thao nam.</p><h3>Nên chọn size áo thể thao nam như thế nào?</h3><p>Bạn nên chọn theo số đo vai, ngực và thói quen mặc ôm hay rộng. Nếu phân vân giữa hai size, hãy ưu tiên size tạo cảm giác thoải mái khi vận động.</p><h3>Chất liệu premium cotton có dễ chăm sóc không?</h3><p>Nên giặt nhẹ, phơi nơi thoáng và tránh chất tẩy mạnh để giữ bề mặt vải và form dáng ổn định hơn.</p><p><strong>Gợi ý từ URSport:</strong> nếu bạn cần một mẫu áo nam dễ mặc, rõ chất liệu và dễ phối, Áo Thun Nam UR BEE Premium Cotton là bản nháp sản phẩm tốt để tiếp tục bổ sung ảnh thật, bảng size và thông tin tồn kho trước khi xuất bản.</p>`,
    price: 119000,
    images: ['/images/products/ao-thun-nam-ur-bee-premium-cotton-mau-den.webp', '/images/products/ao-thun-nam-ur-bee-premium-cotton-mau-trang.webp', '/images/products/ao-thun-nam-ur-bee-premium-cotton-mau-xam-tieu.webp', '/images/products/ao-thun-nam-ur-bee-premium-cotton-mau-xanh-den.webp'],
    category: `Áo thun thể thao nam`,
    colors: ['Đen', 'Trắng', 'Xanh đen'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL', '4XL'],
    stock: 90,
    rating: 5,
    reviewsCount: 0,
    features: [],
    seoTitle: `áo thể thao nam premium cotton URSport`,
    metaDescription: `Áo Thun Nam UR BEE Premium Cotton chất liệu premium cotton, form regular fit, dễ mặc hằng ngày. Xem size, màu và đặt mua tại URSport.`,
    keywords: `áo thể thao nam ursport, áo thể thao nam premium cotton, áo thể thao nam regular fit, áo nam đen, trắng, xanh đen`,
    specifications: ``,
    brand: `URSport`,
    isNew: true
  },
  {
    id: `59cfdb0a-1a40-4717-93c1-c20625fa6ea4`,
    productCode: `UR-59CFDB0A`,
    slug: `ao-thun-nam-ursport-premium-cotton-mem-mai-thoang-mat-chuan-form-nam-tinh`,
    name: `Áo Thun Nam URSPORT Premium Cotton - Mềm Mại, Thoáng Mát, Chuẩn Form`,
    description: `<p>Chào đón sự thoải mái và phong cách với <strong>Áo Thun Nam URSPORT Premium Cotton - Mềm Mại, Thoáng Mát, Chuẩn Form Nam Tính</strong>. Đây là item không thể thiếu trong tủ đồ của quý ông hiện đại, tìm kiếm sự kết hợp hoàn hảo giữa chất lượng, sự tiện dụng và vẻ ngoài chỉn chu. Được làm từ chất liệu premium cotton cao cấp, chiếc áo này hứa hẹn mang lại cảm giác dễ chịu tối đa cùng form dáng regular fit tôn lên vẻ nam tính, gọn gàng trong mọi khoảnh khắc.</p><h2>Vì sao Áo Thun Nam URSPORT Premium Cotton là lựa chọn lý tưởng?</h2><p>Khi chọn <a href="/ao-thun-nam">áo thun nam</a>, điều bạn quan tâm nhất chắc chắn là cảm giác mặc, độ bền và khả năng phối đồ linh hoạt. Áo Thun Nam URSPORT Premium Cotton được thiết kế để đáp ứng mọi kỳ vọng đó, mang đến một phong cách basic nhưng vẫn toát lên vẻ sạch sẽ, khỏe khoắn và đầy nam tính. Đây không chỉ là một chiếc áo, mà là tuyên ngôn về sự tinh tế trong sự đơn giản.</p><ul><li><strong>Chất liệu cao cấp:</strong> Premium cotton mềm mại, thân thiện với làn da, mang lại cảm giác dễ chịu suốt cả ngày dài.</li><li><strong>Form dáng chuẩn:</strong> Regular fit ôm vừa vặn, giúp bạn trông gọn gàng nhưng vẫn đảm bảo sự thoải mái tối đa khi vận động.</li><li><strong>Màu sắc đa năng:</strong> Với các gam màu Đen, Trắng, Xanh đen, chiếc áo dễ dàng kết hợp với mọi trang phục, từ quần jeans năng động đến quần thể thao khỏe khoắn.</li><li><strong>Đa dạng kích cỡ:</strong> Bảng size rộng từ M đến 4XL, giúp mọi quý ông dễ dàng tìm được chiếc áo ưng ý, vừa vặn với vóc dáng.</li></ul><h2>Bí quyết cho cảm giác mặc tuyệt vời: Chất liệu Premium Cotton</h2><p>URSport luôn đặt trải nghiệm của người mặc lên hàng đầu. Với chất liệu premium cotton, chiếc áo này không chỉ mềm mại khi chạm vào mà còn cực kỳ thoáng khí, giúp bạn luôn cảm thấy mát mẻ và khô ráo, ngay cả trong những ngày dài năng động. Bề mặt vải dễ chịu, không gây kích ứng, là lựa chọn hoàn hảo cho những ai yêu thích sự thoải mái tự nhiên và phong cách thể thao nam hiện đại.</p><p>Nếu bạn đang xây dựng một tủ đồ nam cơ bản, một mẫu áo có chất liệu tốt như <a href="/ao-thun-nam/cotton">áo thun nam cotton</a> cao cấp sẽ giúp bạn tự tin hơn, giảm bớt lo lắng về việc phải thay đổi trang phục quá nhiều trong ngày. Chiếc áo này dễ dàng kết hợp cùng quần jeans, jogger hay quần short, tạo nên set đồ gọn gàng, năng động và đầy cá tính.</p><h2>Phong cách không cần gắng sức với Form Regular Fit</h2><p>Form regular fit của áo là sự cân bằng hoàn hảo giữa vẻ ngoài chỉn chu và sự thoải mái tối đa. Không quá ôm sát, cũng không quá rộng thùng thình, chiếc áo giúp tôn lên vóc dáng tự nhiên của bạn, mang lại vẻ ngoài thanh lịch và năng động. Dù bạn đi làm trong môi trường thoải mái, dạo phố cùng bạn bè, du lịch ngắn ngày hay tập luyện nhẹ, sản phẩm vẫn giữ được vẻ đơn giản, dễ gần và không hề xuề xòa.</p><p>Với các màu sắc cơ bản như Đen, Trắng, Xanh đen, bạn có thể thỏa sức sáng tạo phong cách: tối giản cùng quần tây hoặc quần đen, năng động với quần thể thao, hoặc casual với quần jeans. Sự linh hoạt này giúp chiếc áo trở thành một item đa năng, phù hợp với nhiều bối cảnh khác nhau trong cuộc sống hàng ngày.</p><h2>Áo Thun Nam URSPORT: Người bạn đồng hành mỗi ngày</h2><p>Chiếc áo này sinh ra dành cho những quý ông ưu tiên sự rõ ràng và chất lượng. Bạn biết mình cần một chiếc áo với chất liệu tốt, form dáng chuẩn, màu sắc dễ phối và mức giá hợp lý. Đây là sản phẩm dành cho bạn – người không muốn đọc những lời quảng cáo hoa mỹ, mà cần một mô tả chân thực về trải nghiệm mặc, khả năng phối đồ và cách chọn size.</p><p>Nếu bạn đang tìm kiếm một mẫu áo để mặc thường xuyên, đi chơi cuối tuần hoặc phối cùng outfit thể thao nhẹ, Áo Thun Nam URSPORT Premium Cotton chính là lựa chọn lý tưởng bởi tính dễ dùng và sự thoải mái vượt trội. Với URSport, bạn không chỉ mua một chiếc áo, mà là đầu tư vào sự tự tin và phong cách bền vững.</p><h2>Trước khi thêm vào giỏ hàng: Một vài lưu ý nhỏ</h2><p>Để đảm bảo bạn hoàn toàn hài lòng với lựa chọn của mình, URSport gợi ý bạn kiểm tra lại một vài điểm sau:</p><ul><li><strong>Màu sắc yêu thích:</strong> Xác nhận lại bạn đã chọn đúng màu Đen, Trắng hoặc Xanh đen mong muốn.</li><li><strong>Kích cỡ hoàn hảo:</strong> Đối chiếu bảng size M, L, XL, XXL, 3XL, 4XL với số đo cơ thể để tìm ra size vừa vặn nhất.</li><li><strong>Cảm nhận chất liệu:</strong> Hãy hình dung về chất liệu premium cotton mềm mại và form regular fit thoải mái để đảm bảo đúng kỳ vọng của bạn.</li></ul><p>Những bước kiểm tra đơn giản này sẽ giúp bạn tự tin hơn khi sở hữu chiếc áo thun nam premium cotton từ URSport.</p><h2>Hướng dẫn chọn size áo thun nam chuẩn xác</h2><p>URSport hiểu rằng việc chọn size áo online đôi khi có thể khiến bạn băn khoăn. Các size hiện có gồm <strong>M, L, XL, XXL, 3XL, 4XL</strong>. Để chọn được chiếc áo ưng ý nhất, hãy ưu tiên số đo vai và vòng ngực của bạn trước. Sau đó, cân nhắc thói quen mặc ôm hay rộng.</p><p>Nếu bạn là người yêu thích vận động hoặc muốn cảm giác thoải mái tối đa cả ngày, hãy chọn size tạo dư nhẹ ở vai và ngực. Để có lựa chọn chính xác hơn nữa, đừng ngần ngại tham khảo <a href="/blog/bang-size-ao-thun-nam">bảng size áo thun nam</a> chi tiết của chúng tôi. Trong trường hợp số đo của bạn nằm giữa hai size, lựa chọn an toàn thường là size lớn hơn, đặc biệt nếu bạn thích mặc thoáng hoặc phối layer.</p><h2>Bí quyết giữ áo bền đẹp như mới</h2><p>Để chiếc áo thun nam premium cotton của bạn luôn giữ được form dáng và chất lượng như ngày đầu, hãy lưu ý một vài mẹo chăm sóc đơn giản sau:</p><ul><li>Giặt ở chế độ nhẹ nhàng, tránh ngâm áo quá lâu với các chất tẩy rửa mạnh.</li><li>Luôn lộn trái áo trước khi giặt để bảo vệ bề mặt vải và hình in (nếu có).</li><li>Phơi áo ở nơi thoáng mát, tránh ánh nắng gắt trực tiếp trong thời gian dài để giữ màu và độ bền vải.</li><li>Ủi ở nhiệt độ thấp, phù hợp với chất liệu cotton để tránh làm hỏng sợi vải.</li></ul><h2>Câu hỏi thường gặp</h2><h3>Áo Thun Nam URSPORT Premium Cotton - Mềm Mại, Thoáng Mát, Chuẩn Form Nam Tính phù hợp mặc khi nào?</h3><p>Sản phẩm phù hợp mặc hằng ngày, đi chơi, di chuyển nhẹ và phối cùng quần thể thao nam.</p><h3>Nên chọn size áo thun nam như thế nào?</h3><p>Bạn nên chọn theo số đo vai, ngực và thói quen mặc ôm hay rộng. Nếu phân vân giữa hai size, hãy ưu tiên size tạo cảm giác thoải mái khi vận động.</p><h3>Chất liệu premium cotton có dễ chăm sóc không?</h3><p>Nên giặt nhẹ, phơi nơi thoáng và tránh chất tẩy mạnh để giữ bề mặt vải và form dáng ổn định hơn.</p>`,
    price: 119000,
    images: ['/images/products/491b0a87-8deb-433b-93fc-68634791af14-1.png'],
    category: `Áo thun nam`,
    colors: ['Đen', 'Trắng', 'Xanh đen'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL', '4XL'],
    stock: 90,
    rating: 5,
    reviewsCount: 0,
    features: [],
    seoTitle: `áo thun nam premium cotton URSport`,
    metaDescription: `Áo Thun Nam URSPORT Premium Cotton - Mềm Mại, Thoáng Mát, Chuẩn Form Nam Tính chất liệu premium cotton, form regular fit, dễ mặc hằng ngày. Xem size, màu`,
    keywords: `áo thun nam ursport, áo thun nam premium cotton, áo thun nam regular fit, áo nam đen, trắng, xanh đen`,
    specifications: ``,
    brand: `URSport`,
    isNew: true
  },
  {
    id: `788191fd-fd54-4541-a389-5170ec7064ea`,
    productCode: `UR-788191FD`,
    slug: `ao-polo-nam-co-be-ursport-mem-mai-thoang-mat-chuan-form-nam-tinh`,
    name: `Áo polo nam cổ bẻ ursport - Mềm Mại, Thoáng Mát, Chuẩn Form Nam Tính`,
    description: `<p><strong>Áo polo nam cổ bẻ ursport - Mềm Mại, Thoáng Mát, Chuẩn Form Nam Tính</strong> là lựa chọn dành cho nam giới muốn có một mẫu áo dễ mặc, gọn form và đủ chỉn chu cho nhiều hoàn cảnh. Sản phẩm tập trung vào cảm giác mặc thực tế: chất liệu premium cotton, form regular fit, màu Đen, Trắng, Xanh đen và bảng size rõ ràng để người mua chọn nhanh hơn.</p><h2>Điểm nổi bật của áo polo nam premium cotton</h2><p>Khi chọn <a href="/ao-thun-nam">áo thun nam</a>, khách hàng thường quan tâm nhất đến độ thoải mái, độ bền form và khả năng phối đồ. Áo polo nam cổ bẻ ursport - Mềm Mại, Thoáng Mát, Chuẩn Form Nam Tính được định vị theo hướng basic premium: không cầu kỳ, không quá phô trương, nhưng vẫn tạo cảm giác sạch, khỏe và nam tính.</p><ul><li><strong>Chất liệu:</strong> premium cotton cho cảm giác mềm và dễ chịu khi mặc lâu.</li><li><strong>Form:</strong> regular fit giúp tổng thể gọn hơn nhưng vẫn đủ khoảng thở khi vận động.</li><li><strong>Màu sắc:</strong> Đen, Trắng, Xanh đen phù hợp nhiều kiểu quần và giày.</li><li><strong>Size:</strong> M, L, XL, XXL, 3XL, 4XL giúp khách dễ chọn theo vóc dáng.</li></ul><h2>Chất liệu và cảm giác mặc</h2><p>Với chất liệu premium cotton, sản phẩm hướng đến cảm giác mặc ổn định trong nhịp sống hằng ngày. Nội dung sản phẩm không bịa thêm thông số kỹ thuật ngoài dữ liệu đầu vào, nhưng vẫn mô tả rõ giá trị mà khách hàng có thể cảm nhận: bề mặt vải dễ chịu, dễ phối và phù hợp phong cách thể thao nam hiện đại.</p><p>Nếu bạn đang xây dựng tủ đồ nam cơ bản, một mẫu áo có chất liệu tốt sẽ giúp giảm cảm giác phải thay đổi trang phục quá nhiều trong ngày. Áo có thể đi cùng jeans, jogger hoặc <a href="/blog/bang-size-ao-thun-nam">bảng size áo thun nam</a> để tạo set đồ gọn, năng động.</p><h2>Form dáng và phong cách phối đồ</h2><p>Form regular fit phù hợp người thích sự cân bằng giữa thoải mái và chỉn chu. Khi mặc đi làm môi trường thoải mái, đi cà phê, du lịch ngắn ngày hoặc tập luyện nhẹ, sản phẩm vẫn giữ được vẻ đơn giản, dễ gần và không bị quá xuề xòa.</p><p>Với màu Đen, Trắng, Xanh đen, bạn có thể phối theo 3 hướng: tối giản với quần đen, năng động với quần thể thao, hoặc casual với quần jeans. Cách phối này giúp sản phẩm có tính ứng dụng cao hơn thay vì chỉ dùng cho một bối cảnh.</p><h2>Ai nên chọn mẫu áo này?</h2><p>Áo polo nam cổ bẻ ursport - Mềm Mại, Thoáng Mát, Chuẩn Form Nam Tính phù hợp với người mua ưu tiên sự rõ ràng: biết mình cần chất liệu gì, form gì, màu gì và mức giá bao nhiêu. Đây là nhóm khách không muốn đọc lời quảng cáo quá đà, mà cần mô tả sản phẩm đủ cụ thể để ra quyết định nhanh. Vì vậy nội dung sản phẩm nên nói thẳng vào trải nghiệm mặc, khả năng phối đồ và cách chọn size.</p><p>Nếu khách hàng đang tìm một mẫu áo để mặc thường xuyên, đi chơi cuối tuần hoặc phối với outfit thể thao nhẹ, sản phẩm có lợi thế ở tính dễ dùng. Nếu khách cần một mẫu chuyên dụng cho vận động cường độ cao, trang sản phẩm nên bổ sung thêm dữ liệu thật về độ co giãn, độ thoáng hoặc ảnh test thực tế trước khi khẳng định sâu hơn.</p><h2>Checklist trước khi đặt mua</h2><ul><li>Kiểm tra đúng màu muốn mua: Đen, Trắng, Xanh đen.</li><li>Đối chiếu size M, L, XL, XXL, 3XL, 4XL với số đo cá nhân.</li><li>Xem ảnh mặt trước, ảnh chi tiết chất liệu và ảnh mặc thật nếu shop đã bổ sung.</li><li>Đọc kỹ phần chất liệu premium cotton và form regular fit để tránh chọn sai kỳ vọng.</li></ul><p>Checklist này giúp khách hàng tự tin hơn trước khi thêm sản phẩm vào giỏ. Với ecommerce thời trang, mô tả tốt không chỉ để lên SEO mà còn phải giảm câu hỏi lặp lại về size, màu và cảm giác mặc.</p><h2>Gợi ý ảnh nên bổ sung cho sản phẩm</h2><p>Để trang sản phẩm mạnh hơn, nên có ít nhất 3 nhóm ảnh: ảnh chính rõ toàn bộ áo, ảnh cận chất liệu/đường may và ảnh mặc thật trên người mẫu nam. Nếu có đủ ảnh, hệ thống Image SEO sẽ tạo fileName, alt, title và caption riêng cho từng ảnh để hỗ trợ Google hiểu đúng sản phẩm.</p><p>Ảnh chính nên sạch nền, không che sản phẩm và không dùng chữ quá lớn trên ảnh. Ảnh lifestyle nên thể hiện cách phối thật với quần và giày để người mua hình dung sản phẩm trong đời sống hằng ngày.</p><h2>Hướng dẫn chọn size</h2><p>Các size hiện có gồm <strong>M, L, XL, XXL, 3XL, 4XL</strong>. Khi chọn size, hãy ưu tiên số đo vai và vòng ngực trước, sau đó mới cân nhắc thói quen mặc ôm hay rộng. Người thích vận động hoặc muốn thoải mái cả ngày có thể chọn size tạo dư nhẹ ở vai và ngực.</p><p>Để chọn chính xác hơn, bạn có thể tham khảo <a href="/ao-thun-nam">áo thun nam</a>. Nếu số đo nằm giữa hai size, lựa chọn an toàn thường là size lớn hơn, đặc biệt khi bạn thích mặc thoáng hoặc phối layer.</p><h2>Cách chăm sóc để áo bền đẹp</h2><ul><li>Giặt ở chế độ nhẹ, tránh ngâm quá lâu với chất tẩy mạnh.</li><li>Lộn trái áo trước khi giặt để giảm ma sát bề mặt.</li><li>Phơi nơi thoáng, hạn chế nắng gắt trực tiếp trong thời gian dài.</li><li>Ủi ở nhiệt độ phù hợp với chất liệu vải.</li></ul><h2>Câu hỏi thường gặp</h2><h3>Áo polo nam cổ bẻ ursport - Mềm Mại, Thoáng Mát, Chuẩn Form Nam Tính phù hợp mặc khi nào?</h3><p>Sản phẩm phù hợp mặc hằng ngày, đi chơi, di chuyển nhẹ và phối cùng quần thể thao nam.</p><h3>Nên chọn size value=>{const normalized=slugify(value);const labels={"ao-thun-nam":"\xE1o thun nam","ao-the-thao-nam":"\xE1o th\u1EC3 thao nam","ao-polo-nam":"\xE1o polo nam","quan-the-thao-nam":"qu\u1EA7n th\u1EC3 thao nam"};return labels[normalized]||value.replace(/-/g," ")} như thế nào?</h3><p>Bạn nên chọn theo số đo vai, ngực và thói quen mặc ôm hay rộng. Nếu phân vân giữa hai size, hãy ưu tiên size tạo cảm giác thoải mái khi vận động.</p><h3>Chất liệu premium cotton có dễ chăm sóc không?</h3><p>Nên giặt nhẹ, phơi nơi thoáng và tránh chất tẩy mạnh để giữ bề mặt vải và form dáng ổn định hơn.</p><p><strong>Gợi ý từ URSport:</strong> nếu bạn cần một mẫu áo nam dễ mặc, rõ chất liệu và dễ phối, Áo polo nam cổ bẻ ursport - Mềm Mại, Thoáng Mát, Chuẩn Form Nam Tính là bản nháp sản phẩm tốt để tiếp tục bổ sung ảnh thật, bảng size và thông tin tồn kho trước khi xuất bản.</p>`,
    price: 119000,
    images: ['/images/products/ao-polo-nam.png'],
    category: `Áo polo nam`,
    colors: ['Đen', 'Trắng', 'Xanh đen'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL', '4XL'],
    stock: undefined,
    rating: 5,
    reviewsCount: 0,
    features: [],
    seoTitle: `áo polo nam premium cotton URSport`,
    metaDescription: `Áo polo nam cổ bẻ ursport - Mềm Mại, Thoáng Mát, Chuẩn Form Nam Tính chất liệu premium cotton, form regular fit, dễ mặc hằng ngày. Xem size, màu và đặt`,
    keywords: `áo polo nam ursport, áo polo nam premium cotton, áo polo nam regular fit, áo nam đen, trắng, xanh đen`,
    specifications: ``,
    brand: `URSport`,
    isNew: true
  },
  {
    id: `7c6efcb5-4848-423d-9b67-d4ce7a87a0a7`,
    productCode: `UR-7C6EFCB5`,
    slug: `ao-thun-nam-ursport-premium-cotton`,
    name: `Ao Thun Nam URSport Premium Cotton`,
    description: `<p><strong>�o Thun Nam AETHER Premium Cotton</strong> là lựa chọn dành cho nam giới muốn có một mẫu áo dễ mặc, gọn form và đủ chỉn chu cho nhiều hoàn cảnh. Sản phẩm tập trung vào cảm giác mặc thực tế: chất liệu premium cotton, form regular fit, màu Den, Tr?ng, Xanh den và bảng size rõ ràng để người mua chọn nhanh hơn.</p><h2>Điểm nổi bật của ao thun nam premium cotton</h2><p>Khi chọn <a href="/ao-thun-nam">áo thun nam</a>, khách hàng thường quan tâm nhất đến độ thoải mái, độ bền form và khả năng phối đồ. �o Thun Nam AETHER Premium Cotton được định vị theo hướng basic premium: không cầu kỳ, không quá phô trương, nhưng vẫn tạo cảm giác sạch, khỏe và nam tính.</p><ul><li><strong>Chất liệu:</strong> premium cotton cho cảm giác mềm và dễ chịu khi mặc lâu.</li><li><strong>Form:</strong> regular fit giúp tổng thể gọn hơn nhưng vẫn đủ khoảng thở khi vận động.</li><li><strong>Màu sắc:</strong> Den, Tr?ng, Xanh den phù hợp nhiều kiểu quần và giày.</li><li><strong>Size:</strong> M, L, XL giúp khách dễ chọn theo vóc dáng.</li></ul><h2>Chất liệu và cảm giác mặc</h2><p>Với chất liệu premium cotton, sản phẩm hướng đến cảm giác mặc ổn định trong nhịp sống hằng ngày. Nội dung sản phẩm không bịa thêm thông số kỹ thuật ngoài dữ liệu đầu vào, nhưng vẫn mô tả rõ giá trị mà khách hàng có thể cảm nhận: bề mặt vải dễ chịu, dễ phối và phù hợp phong cách thể thao nam hiện đại.</p><p>Nếu bạn đang xây dựng tủ đồ nam cơ bản, một mẫu áo có chất liệu tốt sẽ giúp giảm cảm giác phải thay đổi trang phục quá nhiều trong ngày. Áo có thể đi cùng jeans, jogger hoặc <a href="/ao-thun-nam/cotton">áo thun nam cotton</a> để tạo set đồ gọn, năng động.</p><h2>Form dáng và phong cách phối đồ</h2><p>Form regular fit phù hợp người thích sự cân bằng giữa thoải mái và chỉn chu. Khi mặc đi làm môi trường thoải mái, đi cà phê, du lịch ngắn ngày hoặc tập luyện nhẹ, sản phẩm vẫn giữ được vẻ đơn giản, dễ gần và không bị quá xuề xòa.</p><p>Với màu Den, Tr?ng, Xanh den, bạn có thể phối theo 3 hướng: tối giản với quần đen, năng động với quần thể thao, hoặc casual với quần jeans. Cách phối này giúp sản phẩm có tính ứng dụng cao hơn thay vì chỉ dùng cho một bối cảnh.</p><h2>Hướng dẫn chọn size</h2><p>Các size hiện có gồm <strong>M, L, XL</strong>. Khi chọn size, hãy ưu tiên số đo vai và vòng ngực trước, sau đó mới cân nhắc thói quen mặc ôm hay rộng. Người thích vận động hoặc muốn thoải mái cả ngày có thể chọn size tạo dư nhẹ ở vai và ngực.</p><p>Để chọn chính xác hơn, bạn có thể tham khảo <a href="/blog/bang-size-ao-thun-nam">bảng size áo thun nam</a>. Nếu số đo nằm giữa hai size, lựa chọn an toàn thường là size lớn hơn, đặc biệt khi bạn thích mặc thoáng hoặc phối layer.</p><h2>Cách chăm sóc để áo bền đẹp</h2><ul><li>Giặt ở chế độ nhẹ, tránh ngâm quá lâu với chất tẩy mạnh.</li><li>Lộn trái áo trước khi giặt để giảm ma sát bề mặt.</li><li>Phơi nơi thoáng, hạn chế nắng gắt trực tiếp trong thời gian dài.</li><li>Ủi ở nhiệt độ phù hợp với chất liệu vải.</li></ul><h2>Câu hỏi thường gặp</h2><h3>�o Thun Nam AETHER Premium Cotton phù hợp mặc khi nào?</h3><p>Sản phẩm phù hợp mặc hằng ngày, đi chơi, di chuyển nhẹ và phối cùng quần thể thao nam.</p><h3>Nên chọn size ao thun nam như thế nào?</h3><p>Bạn nên chọn theo số đo vai, ngực và thói quen mặc ôm hay rộng. Nếu phân vân giữa hai size, hãy ưu tiên size tạo cảm giác thoải mái khi vận động.</p><h3>Chất liệu premium cotton có dễ chăm sóc không?</h3><p>Nên giặt nhẹ, phơi nơi thoáng và tránh chất tẩy mạnh để giữ bề mặt vải và form dáng ổn định hơn.</p><p><strong>Gợi ý từ URSport:</strong> nếu bạn cần một mẫu áo nam dễ mặc, rõ chất liệu và dễ phối, �o Thun Nam AETHER Premium Cotton là bản nháp sản phẩm tốt để tiếp tục bổ sung ảnh thật, bảng size và thông tin tồn kho trước khi xuất bản.</p><p>Gợi ý sử dụng 1: Ao Thun Nam URSport Premium Cotton phù hợp với người mua cần một sản phẩm rõ chất liệu, dễ phối và có thông tin size minh bạch. Nội dung này giúp khách hàng hiểu bối cảnh sử dụng, cách chăm sóc và lý do nên chọn sản phẩm theo nhu cầu thật thay vì chỉ nhìn vào tên gọi.</p><p>Gợi ý sử dụng 2: Ao Thun Nam URSport Premium Cotton phù hợp với người mua cần một sản phẩm rõ chất liệu, dễ phối và có thông tin size minh bạch. Nội dung này giúp khách hàng hiểu bối cảnh sử dụng, cách chăm sóc và lý do nên chọn sản phẩm theo nhu cầu thật thay vì chỉ nhìn vào tên gọi.</p><p>Gợi ý sử dụng 3: Ao Thun Nam URSport Premium Cotton phù hợp với người mua cần một sản phẩm rõ chất liệu, dễ phối và có thông tin size minh bạch. Nội dung này giúp khách hàng hiểu bối cảnh sử dụng, cách chăm sóc và lý do nên chọn sản phẩm theo nhu cầu thật thay vì chỉ nhìn vào tên gọi.</p><p>Gợi ý sử dụng 4: Ao Thun Nam URSport Premium Cotton phù hợp với người mua cần một sản phẩm rõ chất liệu, dễ phối và có thông tin size minh bạch. Nội dung này giúp khách hàng hiểu bối cảnh sử dụng, cách chăm sóc và lý do nên chọn sản phẩm theo nhu cầu thật thay vì chỉ nhìn vào tên gọi.</p><p>Gợi ý sử dụng 5: Ao Thun Nam URSport Premium Cotton phù hợp với người mua cần một sản phẩm rõ chất liệu, dễ phối và có thông tin size minh bạch. Nội dung này giúp khách hàng hiểu bối cảnh sử dụng, cách chăm sóc và lý do nên chọn sản phẩm theo nhu cầu thật thay vì chỉ nhìn vào tên gọi.</p>`,
    price: 119000,
    images: [],
    category: `Áo thun nam`,
    colors: ['Den', 'Tr?ng', 'Xanh den'],
    sizes: ['M', 'L', 'XL'],
    stock: undefined,
    rating: 5,
    reviewsCount: 0,
    features: [],
    seoTitle: `ao thun nam premium cotton URSport`,
    metaDescription: `�o Thun Nam AETHER Premium Cotton chất liệu premium cotton, form regular fit, dễ mặc hằng ngày. Xem size, màu và đặt mua tại URSport.`,
    keywords: `ao thun nam ursport, ao thun nam premium cotton, ao thun nam regular fit, áo nam den, tr?ng, xanh den`,
    specifications: ``,
    brand: `URSport`,
    isNew: true
  },
  // --- ÁO THUN NAM (8 products) ---
  {
    id: 'at-1',
    slug: 'ao-thun-cotton-starship-premium',
    name: 'Áo Thun Cotton Starship Premium',
    description: 'Chất liệu 100% cotton tự nhiên cao cấp, in logo Starship Entertainment tinh tế. Form dáng hiện đại, thoáng mát.',
    price: 250000,
    category: 'Áo thun nam',
    images: [
      '/images/ao-thun-nam.webp',
      '/images/ao-thun-the-thao-nam.webp',
      '/images/ao-polo-nam.webp',
      '/images/quan-the-thao-nam.webp',
      '/images/phu-kien-the-thao.webp'
    ],
    colors: ['Trắng', 'Đen', 'Đỏ', 'Vàng', 'Than', 'Xanh'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL', '4XL'],
    stock: 50,
    rating: 4.8,
    reviewsCount: 120,
    features: ['Cotton 100%', 'In logo bền màu', 'Form chuẩn US'],
    isBestSeller: true
  },
  {
    id: 'at-2',
    slug: 'ao-thun-graphic-run-fast',
    name: 'Áo Thun Graphic "Run Fast"',
    description: 'Thiết kế graphic năng động, cá tính. Form áo rộng thoải mái.',
    price: 320000,
    discountPrice: 250000,
    category: 'Áo thun nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Vàng', 'Đen'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL', '4XL'],
    stock: 30,
    rating: 4.5,
    reviewsCount: 45,
    features: ['In lụa cao cấp', 'Cotton 4 chiều', 'Không xù lông'],
    isNew: true
  },
  {
    id: 'at-3',
    slug: 'ao-thun-oversize-urstyle',
    name: 'Áo Thun Oversize UrStyle',
    description: 'Phong cách đường phố hiện đại, form dáng cực chuẩn cho giới trẻ.',
    price: 350000,
    category: 'Áo thun nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Xanh Rêu', 'Be', 'Đen'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL', '4XL'],
    stock: 40,
    rating: 4.7,
    reviewsCount: 78,
    features: ['Vải dày dặn', 'Form rộng', 'Fashionable']
  },
  {
    id: 'at-4',
    slug: 'ao-thun-henley-co-nut',
    name: 'Áo Thun Henley Cổ Nút',
    description: 'Thiết kế cổ nút tinh tế, mang lại vẻ ngoài lịch lãm nhưng vẫn trẻ trung.',
    price: 380000,
    category: 'Áo thun nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Xám Ghi', 'Xanh Than'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL', '4XL'],
    stock: 25,
    rating: 4.6,
    reviewsCount: 32,
    features: ['Cổ bẻ có nút', 'Vải cotton xốp', 'Dễ phối đồ']
  },
  {
    id: 'at-5',
    slug: 'ao-thun-soc-ngang-urban',
    name: 'Áo Thun Sọc Ngang Urban',
    description: 'Họa tiết sọc ngang kinh điển, trẻ trung và không bao giờ lỗi mốt.',
    price: 290000,
    category: 'Áo thun nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Trắng-Xanh', 'Trắng-Đen'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL', '4XL'],
    stock: 15,
    rating: 4.4,
    reviewsCount: 28,
    features: ['Sọc dệt trực tiếp', 'Mát tay', 'Vải nhẹ']
  },
  {
    id: 'at-6',
    slug: 'ao-thun-pocket-tee',
    name: 'Áo Thun Pocket Tee',
    description: 'Điểm nhấn túi ngực nhỏ gọn, tinh tế và tiện lợi.',
    price: 270000,
    category: 'Áo thun nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Hồng Pastel', 'Xanh Mint', 'Trắng'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL', '4XL'],
    stock: 20,
    rating: 4.3,
    reviewsCount: 15,
    features: ['Túi ngực thật', 'Vải mềm mịn', 'Kháng khuẩn']
  },
  {
    id: 'at-7',
    slug: 'ao-thun-longline-modern',
    name: 'Áo Thun Longline Modern',
    description: 'Vạt bầu dài thời trang, cực kỳ phù hợp cho phong cách layer.',
    price: 360000,
    category: 'Áo thun nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Đen', 'Trắng'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL', '4XL'],
    stock: 12,
    rating: 4.9,
    reviewsCount: 64,
    features: ['Vạt bầu dài', 'Cổ tròn rộng', 'Phong cách Layer'],
    isNew: true
  },
  {
    id: 'at-8',
    slug: 'ao-thun-in-chim-stealth',
    name: 'Áo Thun In Chìm Stealth',
    description: 'Logo in chìm tinh tế, chỉ lộ rõ dưới ánh sáng mạnh. Đầy bí ẩn và đẳng cấp.',
    price: 390000,
    category: 'Áo thun nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Đen Carbon', 'Xám Đậm'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL', '4XL'],
    stock: 18,
    rating: 5.0,
    reviewsCount: 10,
    features: ['In phản quang chìm', 'Vải cao cấp', 'Limited Edition']
  },

  // --- ÁO THUN THỂ THAO NAM (8 products) ---
  {
    id: 'att-1',
    slug: 'ao-thun-the-thao-nam-chay-bo-gym-pro-dry-khang-khuan',
    name: 'Áo Thun Thể Thao Nam Chạy Bộ, Tập Gym Cao Cấp Pro-Dry Kháng Khuẩn',
    description: 'Áo thun thể thao nam Pro-Dry với công nghệ dệt 3D siêu thoáng khí, thấm hút mồ hôi cực nhanh, phù hợp cho chạy bộ và tập gym. Thiết kế ôm body khỏe khoắn, chất liệu thun lạnh siêu nhẹ giúp bạn thoải mái trong mọi cử động.',
    price: 350000,
    discountPrice: 280000,
    category: 'Áo thun thể thao nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Xanh Blue', 'Đen', 'Đỏ'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    stock: 100,
    rating: 4.9,
    reviewsCount: 250,
    features: ['Công nghệ thoát ẩm Pro-Dry siêu tốc', 'Vải siêu nhẹ co giãn 4 chiều', 'Kháng khuẩn, khử mùi hôi hiệu quả', 'Phù hợp: Chạy bộ, Gym, Cầu lông'],
    isBestSeller: true,
    seoTitle: 'Áo Thun Thể Thao Nam Pro-Dry | Thoáng Mát, Tập Gym & Chạy Bộ | UR Sport',
    metaDescription: 'Mua ngay áo thun thể thao nam Pro-Dry cao cấp. Áo tập gym, chạy bộ nam thoáng mát, co giãn 4 chiều, khử mùi hôi. Miễn phí vận chuyển toàn quốc!',
    keywords: 'áo thun thể thao nam, áo thể thao nam, áo chạy bộ nam, áo tập gym nam, áo thun lạnh thể thao',
    specifications: '<p><strong>Chất liệu:</strong> 90% Polyester, 10% Spandex<br/><strong>Kiểu dáng:</strong> Slim-fit ôm body<br/><strong>Độ co giãn:</strong> 4 chiều<br/><strong>Trọng lượng:</strong> 120g</p>',
    brand: 'UR Sport',
    origin: 'Việt Nam',
    material: 'Thun lạnh cao cấp',
    fashionStyle: 'Thể thao năng động'
  },
  {
    id: 'att-2',
    slug: 'ao-tanktop-nam-tap-gym-khoe-co-bap-urarmor',
    name: 'Áo Tanktop Nam Tập Gym, Khoét Nách Sâu Khoe Cơ Bắp UrArmor',
    description: 'Áo tanktop nam tập gym thiết kế khoét nách sâu cá tính, chất liệu vải lưới thoáng khí tuyệt đối. Giải pháp hoàn hảo cho những buổi tập cơ lưng xô (Back day) hoặc tập vai, giúp tối ưu biên độ chuyển động.',
    price: 290000,
    category: 'Áo thun thể thao nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Đen', 'Xám', 'Trắng'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    stock: 60,
    rating: 4.7,
    reviewsCount: 110,
    features: ['Thiết kế khoét sâu khoe cơ bắp', 'Vải lưới tổ ong siêu thoáng khí', 'Trọng lượng siêu nhẹ, nhanh khô'],
    seoTitle: 'Áo Tanktop Nam Tập Gym Khoét Sâu Khoe Cơ Bắp UrArmor | UR Sport',
    metaDescription: 'Áo tanktop nam tập gym UR Sport chất liệu thoáng khí, thấm hút mồ hôi, form dáng khoét nách cực ngầu giúp khoe trọn vóc dáng nam tính.',
    keywords: 'áo tanktop nam, áo ba lỗ nam tập gym, áo gym nam, áo khoét nách nam, áo thun thể thao không tay',
    brand: 'UR Sport',
    origin: 'Việt Nam',
    material: 'Lưới Polyester'
  },
  {
    id: 'att-3',
    slug: 'ao-compression-nam-dai-tay-giu-nhiet-tap-gym-da-bong',
    name: 'Áo Compression Nam Dài Tay Giữ Nhiệt, Trợ Lực Tập Gym & Đá Bóng',
    description: 'Áo lót thể thao (Compression) dài tay giúp giữ nhiệt cơ thể, ôm sát tạo áp lực nhẹ lên cơ bắp giúp kích thích tuần hoàn máu, giảm mỏi cơ sau khi tập luyện cường độ cao.',
    price: 450000,
    category: 'Áo thun thể thao nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Đen Stealth', 'Xanh Cobalt'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    stock: 40,
    rating: 4.8,
    reviewsCount: 95,
    features: ['Công nghệ nén cơ (Compression)', 'Giữ nhiệt tốt trong mùa đông', 'Chống tia UV (UPF 50+) khi hoạt động ngoài trời'],
    seoTitle: 'Áo Compression Dài Tay Nam Giữ Nhiệt, Tập Gym, Bóng Đá | UR Sport',
    metaDescription: 'Áo compression dài tay nam cao cấp. Hỗ trợ trợ lực, nén cơ bắp, giữ nhiệt cực tốt. Phù hợp cho tập gym, đá bóng và chạy bộ mùa đông.',
    keywords: 'áo compression nam, áo lót thể thao nam dài tay, áo giữ nhiệt thể thao nam, áo body nam tập gym, áo đá bóng tay dài',
    brand: 'UR Sport',
    material: 'Spandex co giãn cao'
  },
  {
    id: 'att-4',
    slug: 'ao-chay-bo-nam-phan-quang-cao-cap-nightrun',
    name: 'Áo Chạy Bộ Nam Phản Quang Chống Nước Nhẹ NightRun',
    description: 'Thiết kế riêng cho các runner chạy ban đêm hoặc sáng sớm. Áo trang bị dải phản quang 360 độ siêu sáng, kết hợp chất liệu mesh thoáng khí đỉnh cao giúp bạn an toàn và thoải mái chinh phục mọi cự ly.',
    price: 380000,
    category: 'Áo thun thể thao nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Vàng Neon', 'Cam'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    stock: 35,
    rating: 4.6,
    reviewsCount: 50,
    features: ['Dải phản quang 360 độ siêu sáng', 'Chống nước nhẹ (Water-repellent)', 'Vải mesh hở siêu thoáng mát'],
    seoTitle: 'Áo Chạy Bộ Nam Phản Quang NightRun Cao Cấp | UR Sport',
    metaDescription: 'Bảo vệ an toàn khi chạy đêm với áo chạy bộ nam phản quang NightRun. Chất liệu nhẹ mát, thấm mồ hôi cực tốt. Phù hợp chạy bộ, đạp xe.',
    keywords: 'áo chạy bộ nam, áo thể thao phản quang, áo chạy bộ đêm, áo phản quang nam, quần áo chạy bộ',
    brand: 'UR Sport'
  },
  {
    id: 'att-5',
    slug: 'ao-thun-the-thao-nam-co-v-tre-trung-v-neck-sport',
    name: 'Áo Thun Thể Thao Nam Cổ V Trẻ Trung, V-Neck Sport Kháng Khuẩn',
    description: 'Sự kết hợp hoàn hảo giữa thời trang và tính năng. Áo thun cổ chữ V tinh tế giúp cổ trông thon dài hơn, chất vải dệt kim cao cấp kháng khuẩn, chống ám mùi thích hợp mặc đi tập lẫn dạo phố.',
    price: 330000,
    category: 'Áo thun thể thao nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Xanh Mint', 'Trắng', 'Đỏ'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    stock: 45,
    rating: 4.5,
    reviewsCount: 40,
    features: ['Thiết kế Cổ V thời thượng', 'Kháng khuẩn và ngăn ngừa mùi mồ hôi', 'Phù hợp đa phong cách: Thể thao & Casual'],
    isNew: true,
    seoTitle: 'Áo Thun Thể Thao Nam Cổ V Cao Cấp | V-Neck Sport | UR Sport',
    metaDescription: 'Sở hữu ngay áo thun thể thao nam cổ V sành điệu. Chất vải kháng khuẩn, thiết kế nam tính, phù hợp cho việc đi tập và mặc thường ngày.',
    keywords: 'áo thun thể thao nam cổ v, áo thun nam cổ tim thể thao, áo thun nam tập gym cổ v',
    brand: 'UR Sport'
  },
  {
    id: 'att-6',
    slug: 'ao-thun-the-thao-in-hoa-tiet-camo',
    name: 'Áo Thun Thể Thao In Họa Tiết Camo',
    description: 'Họa tiết rằn ri mạnh mẽ, giúp bạn nổi bật trong phòng tập.',
    price: 390000,
    category: 'Áo thun thể thao nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Camo Xám', 'Camo Xanh'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    stock: 28,
    rating: 4.7,
    reviewsCount: 22,
    features: ['In công nghệ 3D', 'Vải Poly-Esther', 'Dày dặn']
  },
  {
    id: 'att-7',
    slug: 'ao-khoac-gio-the-thao-windbreaker',
    name: 'Áo Khoác Gió Thể Thao Windbreaker',
    description: 'Chống gió và mưa nhẹ, lý tưởng cho những buổi tập ngoài trời.',
    price: 650000,
    discountPrice: 550000,
    category: 'Áo thun thể thao nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Đen', 'Xám'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    stock: 15,
    rating: 4.9,
    reviewsCount: 35,
    features: ['Chống nước nhẹ', 'Siêu nhẹ bỏ túi', 'Có mũ trùm'],
    isNew: true
  },
  {
    id: 'att-8',
    slug: 'ao-thun-sat-nach-stringer',
    name: 'Áo Thun Sát Nách Stringer',
    description: 'Dành riêng cho các vận động viên thể hình chuyên nghiệp.',
    price: 250000,
    category: 'Áo thun thể thao nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Vàng Gold', 'Đen', 'Xám'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    stock: 50,
    rating: 4.4,
    reviewsCount: 18,
    features: ['Dây vai mảnh', 'Cotton co giãn', 'Thoáng mát tối đa']
  },

  // --- ÁO POLO NAM (8 products) ---
  {
    id: 'pl-1',
    slug: 'ao-polo-nam-the-thao-golf-classic-lux-cao-cap',
    name: 'Áo Polo Nam Thể Thao Golf Classic Lux Cao Cấp Chống Nhăn',
    description: 'Áo polo nam cao cấp chuyên dụng cho Golf và dạo phố. Form dáng sang trọng, chất liệu vải cá sấu (Pique Cotton) thoáng mát, mang lại vẻ ngoài đẳng cấp và lịch lãm cho phái mạnh.',
    price: 450000,
    category: 'Áo polo nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Trắng', 'Xanh Cyan', 'Đen'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    stock: 45,
    rating: 4.9,
    reviewsCount: 150,
    features: ['Vải Pique Cotton cao cấp', 'Chống nhăn tuyệt đối', 'Cổ áo cứng cáp, không mất form'],
    isBestSeller: true,
    seoTitle: 'Áo Polo Nam Cao Cấp Golf Classic Lux | UR Sport',
    metaDescription: 'Mua áo polo nam thể thao cao cấp cho Golfer. Áo thun có cổ form chuẩn, vải cá sấu mềm mịn, thoáng mát, chống nhăn. Miễn phí đổi trả 7 ngày.',
    keywords: 'áo polo nam, áo thun có cổ nam, áo golf nam, áo polo the thao nam, áo polo nam cao cấp',
    specifications: '<p><strong>Chất liệu:</strong> 95% Pique Cotton, 5% Spandex<br/><strong>Kiểu dáng:</strong> Regular-fit<br/><strong>Cổ áo:</strong> Bẻ cứng cáp</p>',
    brand: 'UR Sport',
    style: 'Thanh lịch, Sang trọng'
  },
  {
    id: 'pl-2',
    slug: 'ao-polo-nam-the-thao-sporty-mesh-thoang-khi',
    name: 'Áo Polo Nam Thể Thao Sporty Mesh Thoáng Khí',
    description: 'Sự kết hợp hoàn hảo giữa vẻ thanh lịch của áo polo truyền thống và sự năng động của đồ thể thao. Áo polo nam Sporty Mesh giúp bạn tự tự tin từ phòng tập đến những buổi gặp gỡ bạn bè.',
    price: 420000,
    discountPrice: 380000,
    category: 'Áo polo nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Đỏ', 'Trắng', 'Navy'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    stock: 30,
    rating: 4.7,
    reviewsCount: 88,
    features: ['Vải thun lạnh Sporty Mesh', 'Logo thêu tinh xảo 3D', 'Siêu thoáng khí, nhanh khô'],
    seoTitle: 'Áo Polo Nam Thể Thao Sporty Mesh | Áo Có Cổ Nam Đẹp | UR Sport',
    metaDescription: 'Áo polo nam thể thao Sporty Mesh cực thoáng mát, thấm mồ hôi tốt. Sự lựa chọn hoàn hảo cho phong cách năng động nhưng vẫn lịch sự. Đặt hàng ngay!',
    keywords: 'áo polo nam thể thao, áo thun nam có cổ thể thao, áo thun lạnh có cổ, áo polo nam đẹp',
    brand: 'UR Sport'
  },
  {
    id: 'pl-3',
    slug: 'ao-polo-nam-phoi-bo-tay-stripe-thoi-trang',
    name: 'Áo Polo Nam Phối Bo Tay Stripe Kẻ Sọc Thời Trang',
    description: 'Điểm nhấn kẻ sọc tinh tế ở cổ và bo tay áo mang lại nét trẻ trung, hiện đại. Áo polo nam Stripe là một item không thể thiếu cho những buổi dạo phố cuối tuần.',
    price: 480000,
    category: 'Áo polo nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Be', 'Xanh Than'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    stock: 25,
    rating: 4.6,
    reviewsCount: 42,
    features: ['Bo tay dệt sọc thể thao', 'Cotton mịn màng thân thiện với da', 'Form Slim Fit tôn dáng'],
    isNew: true,
    seoTitle: 'Áo Polo Nam Kẻ Sọc Phối Bo Tay Thời Trang | UR Sport',
    metaDescription: 'Áo polo nam viền kẻ sọc thời thượng, thiết kế bo tay hiện đại. Áo polo dáng Slim fit giúp tôn lên nét nam tính, trẻ trung.',
    keywords: 'áo polo nam kẻ sọc, áo thun có cổ phối viền, áo polo nam trẻ trung, áo thun cổ bẻ nam',
    brand: 'UR Sport'
  },
  {
    id: 'pl-4',
    slug: 'ao-polo-nam-zipper-tech-khoa-keo',
    name: 'Áo Polo Nam Zipper Tech Khóa Kéo Tương Lai',
    description: 'Thay thế nút bấm truyền thống bằng dây kéo kim loại tinh tế, áo polo nam Zipper Tech tạo nên phong cách thời trang Tech-wear tương lai đầy ấn tượng và khác biệt.',
    price: 520000,
    category: 'Áo polo nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Xám Bạc', 'Đen'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    stock: 20,
    rating: 4.8,
    reviewsCount: 30,
    features: ['Khóa kéo kim loại chống gỉ', 'Vải Spandex co giãn đàn hồi cao', 'Thiết kế tối giản mang hơi hướng Tech-wear'],
    seoTitle: 'Áo Polo Nam Khóa Kéo Zipper Tech Độc Đáo | UR Sport',
    metaDescription: 'Phá cách với áo polo nam khóa kéo Zipper Tech. Vải Spandex co giãn 4 chiều, thiết kế hiện đại, độc quyền tại UR Sport.',
    keywords: 'áo polo nam khóa kéo, áo thun nam có cổ khóa kéo, áo polo nam cao cấp độc lạ, phong cách techwear nam',
    brand: 'UR Sport'
  },
  {
    id: 'pl-5',
    slug: 'ao-polo-nam-det-kim-knit-texture',
    name: 'Áo Polo Nam Dệt Kim Knit Texture Sang Trọng',
    description: 'Bề mặt vải dệt kim (Knit) với cấu trúc vân nổi độc đáo, tạo cảm giác áo rất dày dặn, đứng form và toát lên vẻ sang trọng quyền lực cho người mặc.',
    price: 550000,
    category: 'Áo polo nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Nâu Đất', 'Xanh Rêu'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    stock: 15,
    rating: 4.5,
    reviewsCount: 20,
    features: ['Chất liệu dệt kim Texture cao cấp', 'Giữ form áo xuất sắc sau nhiều lần giặt', 'Giữ ấm nhẹ trong mùa thu đông'],
    seoTitle: 'Áo Polo Nam Dệt Kim Knit Texture Cao Cấp | UR Sport',
    metaDescription: 'Nâng tầm phong cách với áo polo nam dệt kim Knit Texture sang trọng. Chất liệu cao cấp, vân nổi tinh tế. Lựa chọn số 1 của quý ông.',
    keywords: 'áo polo dệt kim nam, áo len mỏng có cổ nam, áo polo nam thu đông, áo thun nam cao cấp',
    brand: 'UR Sport'
  },
  {
    id: 'pl-6',
    slug: 'ao-polo-active-dri-fit',
    name: 'Áo Polo Active Dri-Fit',
    description: 'Dành cho những người yêu thích sự thoải mái tuyệt đối cả ngày dài.',
    price: 390000,
    category: 'Áo polo nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Xám Khói', 'Xanh Pastel'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    stock: 40,
    rating: 4.7,
    reviewsCount: 56,
    features: ['Công nghệ khô nhanh', 'Siêu nhẹ', 'Không cần là ủi']
  },
  {
    id: 'pl-7',
    slug: 'ao-polo-pattern-dot',
    name: 'Áo Polo Pattern Dot',
    description: 'Họa tiết chấm bi nhỏ li ti, tinh tế và lịch sự.',
    price: 490000,
    category: 'Áo polo nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Trắng Chấm Đen', 'Xanh Chấm Trắng'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    stock: 18,
    rating: 4.4,
    reviewsCount: 15,
    features: ['Họa tiết in nhiệt', 'Vải mềm', 'Cổ bẻ thanh lịch']
  },
  {
    id: 'pl-8',
    slug: 'ao-polo-long-sleeve-winter',
    name: 'Áo Polo Long Sleeve Winter',
    description: 'Áo polo tay dài giữ ấm cơ thể trong những ngày se lạnh.',
    price: 580000,
    discountPrice: 450000,
    category: 'Áo polo nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Đen Carbon', 'Xám Lông Chuột'],
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    stock: 10,
    rating: 4.8,
    reviewsCount: 25,
    features: ['Tay dài cổ bẻ', 'Vải giữ nhiệt', 'Lớp lót mềm'],
    isNew: true
  },

  // --- QUẦN THỂ THAO NAM (8 products) ---
  {
    id: 'qt-1',
    slug: 'quan-short-chay-bo-elite-night',
    name: 'Quần Short Chạy Bộ Elite Night',
    description: 'Siêu nhẹ, có túi khóa kéo an toàn. Đai quần co giãn cực tốt.',
    price: 290000,
    discountPrice: 220000,
    category: 'Quần thể thao nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Đen', 'Xám'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 60,
    rating: 4.8,
    reviewsCount: 190,
    features: ['Vải dù siêu nhẹ', 'Túi khóa kéo', 'Phản quang'],
    isBestSeller: true
  },
  {
    id: 'qt-2',
    slug: 'quan-jogger-training-urfocus',
    name: 'Quần Jogger Training UrFocus',
    description: 'Thiết kế bo gấu năng động, chất liệu nỉ da cá thoáng mát.',
    price: 450000,
    category: 'Quần thể thao nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Đen Carbon', 'Xám Ghi'],
    sizes: ['M', 'L', 'XL', '2XL'],
    stock: 45,
    rating: 4.7,
    reviewsCount: 120,
    features: ['Bo gấu thời trang', 'Túi sâu tiện dụng', 'Vải nỉ thoáng'],
    isNew: true
  },
  {
    id: 'qt-3',
    slug: 'quan-dui-tap-gym-2-lop',
    name: 'Quần Đùi Tập Gym 2 Lớp',
    description: 'Tích hợp lớp lót bên trong giúp bảo vệ và hỗ trợ cơ bắp tối ưu.',
    price: 350000,
    category: 'Quần thể thao nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Đen', 'Xanh'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 35,
    rating: 4.9,
    reviewsCount: 85,
    features: ['Thiết kế 2 lớp', 'Túi đựng điện thoại ẩn', 'Co giãn 4 chiều']
  },
  {
    id: 'qt-4',
    slug: 'quan-long-pants-the-thao-pro',
    name: 'Quần Long Pants Thể Thao Pro',
    description: 'Dáng quần ống suông, phù hợp cho cả tập luyện và dạo phố.',
    price: 490000,
    category: 'Quần thể thao nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Xanh Navy', 'Đen'],
    sizes: ['M', 'L', 'XL'],
    stock: 20,
    rating: 4.6,
    reviewsCount: 40,
    features: ['Ống suông hiện đại', 'Dây rút bền bỉ', 'Không nhăn']
  },
  {
    id: 'qt-5',
    slug: 'quan-short-basketball-legend',
    name: 'Quần Short Basketball Legend',
    description: 'Form rộng rãi, phong cách bóng rổ đường phố Mỹ.',
    price: 320000,
    category: 'Quần thể thao nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Đỏ Đen', 'Trắng Đen'],
    sizes: ['M', 'L', 'XL', '3XL'],
    stock: 50,
    rating: 4.5,
    reviewsCount: 30,
    features: ['Lưới thoát khí lớn', 'Cạp cao co giãn', 'Form Oversize']
  },
  {
    id: 'qt-6',
    slug: 'quan-legging-tap-gym-nam',
    name: 'Quần Legging Tập Gym Nam',
    description: 'Mặc bên trong quần đùi, giúp giữ nhiệt và bảo vệ đôi chân.',
    price: 280000,
    category: 'Quần thể thao nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Đen', 'Xám'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 30,
    rating: 4.7,
    reviewsCount: 25,
    features: ['Công nghệ nén cơ', 'Mềm mại', 'Thấm mồ hôi']
  },
  {
    id: 'qt-7',
    slug: 'quan-cargo-sport-da-nang',
    name: 'Quần Cargo Sport Đa Năng',
    description: 'Tích hợp nhiều túi hộp, phong cách quân đội mạnh mẽ.',
    price: 550000,
    category: 'Quần thể thao nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Xanh Rêu', 'Vàng Cát'],
    sizes: ['M', 'L', 'XL'],
    stock: 12,
    rating: 4.4,
    reviewsCount: 14,
    features: ['Nhiều túi tiện ích', 'Vải kaki co giãn', 'Thời trang bụi bặm'],
    isNew: true
  },
  {
    id: 'qt-8',
    slug: 'quan-short-boi-urbeach',
    name: 'Quần Short Bơi UrBeach',
    description: 'Chất liệu mau khô, họa tiết nhiệt đới rực rỡ.',
    price: 260000,
    category: 'Quần thể thao nam',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Họa tiết Summer', 'Xanh Biển'],
    sizes: ['S', 'M', 'L'],
    stock: 100,
    rating: 4.3,
    reviewsCount: 22,
    features: ['Mau khô cực nhanh', 'Lót lưới an toàn', 'In ấn sắc nét']
  },

  // --- PHỤ KIỆN THỂ THAO (8 products) ---
  {
    id: 'pk-1',
    slug: 'binh-nuoc-the-thao-tritan-1l',
    name: 'Bình Nước Thể Thao Tritan 1L',
    description: 'Nhựa cao cấp không chứa BPA, bền chắc và an toàn cho sức khỏe.',
    price: 180000,
    category: 'Phụ kiện thể thao',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Xanh Trong', 'Đen Khói'],
    sizes: ['1000ml'],
    stock: 200,
    rating: 4.9,
    reviewsCount: 320,
    features: ['Nhựa Tritan BPA Free', 'Có vạch chia dung tích', 'Chống va đập'],
    isBestSeller: true
  },
  {
    id: 'pk-2',
    slug: 'tham-yoga-tpe-8mm-sieu-bam',
    name: 'Thảm Yoga TPE 8mm Siêu Bám',
    description: 'Chống trượt tuyệt đối, độ đàn hồi cực tốt bảo vệ khớp xương.',
    price: 350000,
    category: 'Phụ kiện thể thao',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Tím', 'Xanh Dương'],
    sizes: ['183x61cm'],
    stock: 80,
    rating: 4.8,
    reviewsCount: 150,
    features: ['Vật liệu TPE 2 lớp', 'Chống trượt 2 mặt', 'Dễ vệ sinh'],
    isNew: true
  },
  {
    id: 'pk-3',
    slug: 'tui-the-thao-gym-bag-duffel',
    name: 'Túi Thể Thao Gym Bag Duffel',
    description: 'Ngăn chứa đồ rộng rãi, có ngăn đựng giày riêng biệt cực tiện lợi.',
    price: 450000,
    category: 'Phụ kiện thể thao',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Đen Urban', 'Xám Camo'],
    sizes: ['Cỡ Đại'],
    stock: 45,
    rating: 4.7,
    reviewsCount: 95,
    features: ['Ngăn giày riêng', 'Vải chống thấm', 'Quai đeo êm ái']
  },
  {
    id: 'pk-4',
    slug: 'gang-tay-tap-gym-pro-grip',
    name: 'Găng Tay Tập Gym Pro-Grip',
    description: 'Bảo vệ lòng bàn tay khỏi chai sạn, tăng lực bám khi đẩy tạ.',
    price: 150000,
    category: 'Phụ kiện thể thao',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Đen Đỏ', 'Full Đen'],
    sizes: ['M', 'L', 'XL'],
    stock: 120,
    rating: 4.6,
    reviewsCount: 210,
    features: ['Lớp đệm lòng bàn tay', 'Khóa dán cổ tay', 'Thoáng khí']
  },
  {
    id: 'pk-5',
    slug: 'non-ket-the-thao-performance',
    name: 'Nón Kết Thể Thao Performance',
    description: 'Chất liệu vải dù cực nhẹ, form nón chuẩn đẹp.',
    price: 220000,
    category: 'Phụ kiện thể thao',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Trắng', 'Đen', 'Navy'],
    sizes: ['Free Size'],
    stock: 150,
    rating: 4.5,
    reviewsCount: 65,
    features: ['Lỗ thông gió laser', 'Vải dù nhanh khô', 'Khóa gài điều chỉnh']
  },
  {
    id: 'pk-6',
    slug: 'day-nhay-the-luc-speed-rope',
    name: 'Dây Nhảy Thể Lực Speed Rope',
    description: 'Thiết kế khí động học cho tốc độ xoay cực cao.',
    price: 120000,
    category: 'Phụ kiện thể thao',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Đen Red'],
    sizes: ['3m'],
    stock: 100,
    rating: 4.8,
    reviewsCount: 40,
    features: ['Vòng bi xoay 360', 'Dây thép bọc nhựa', 'Chỉnh được độ dài']
  },
  {
    id: 'pk-7',
    slug: 'tat-the-thao-cotton-cushioned',
    name: 'Tất Thể Thao Cotton Cushioned',
    description: 'Lớp đệm dày ở gót và mũi chân giúp giảm chấn thương.',
    price: 45000,
    category: 'Phụ kiện thể thao',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Trắng', 'Đen'],
    sizes: ['Standard'],
    stock: 500,
    rating: 4.7,
    reviewsCount: 180,
    features: ['Cotton 80%', 'Đệm lòng bàn chân', 'Vùng nén vòm chân']
  },
  {
    id: 'pk-8',
    slug: 'bo-5-day-mini-band-khang-luc',
    name: 'Bộ 5 Dây Mini Band Kháng Lực',
    description: 'Hỗ trợ tập luyện mông và chân hiệu quả tại nhà.',
    price: 150000,
    category: 'Phụ kiện thể thao',
    images: ['/images/ao-thun-nam.webp'],
    colors: ['Multicolor'],
    sizes: ['Set 5'],
    stock: 120,
    rating: 4.9,
    reviewsCount: 55,
    features: ['Cao su tự nhiên', '5 mức kháng lực', 'Tặng kèm túi đựng']
  }
];

export const BANNERS = [
  { id: 1, image: '/images/ao-thun-nam.webp', title: 'HIỆU SUẤT VƯỢT TRỘI' },
  { id: 2, image: '/images/ao-thun-the-thao-nam.webp', title: 'THỜI TRANG ĐỈNH CAO' },
  { id: 3, image: '/images/ao-polo-nam.webp', title: 'BỘ SƯU TẬP MỚI' },
  { id: 4, image: '/images/quan-the-thao-nam.webp', title: 'PHÁ VỠ GIỚI HẠN' },
  { id: 5, image: '/images/phu-kien-the-thao.webp', title: 'TỰ TIN TỎA SÁNG' }
];

export const STATIC_BLOG_POSTS: BlogPost[] = [];

export const STATIC_ORDERS: Order[] = [
  { id: 'ord-1001', userId: 'usr-1', items: [{ ...PRODUCTS[0], selectedColor: 'Đen', selectedSize: 'L', quantity: 2 }], total: 500000, status: 'pending', shippingAddress: { fullName: 'Nguyễn Văn A', phone: '0901234567', address: '123 Lê Lợi, Q.1, TP.HCM' }, paymentMethod: 'cod', createdAt: new Date(Date.now() - 10000) },
  { id: 'ord-1002', userId: 'usr-2', items: [{ ...PRODUCTS[15], selectedColor: 'Trắng', selectedSize: 'M', quantity: 1 }, { ...PRODUCTS[20], selectedColor: 'Xám', selectedSize: 'L', quantity: 1 }], total: 850000, status: 'processing', shippingAddress: { fullName: 'Trần Thị B', phone: '0912345678', address: '45 Nguyễn Huệ, Q.1, TP.HCM' }, paymentMethod: 'bank_transfer', createdAt: new Date(Date.now() - 86400000) },
  { id: 'ord-1003', userId: 'usr-3', items: [{ ...PRODUCTS[30], selectedColor: 'Xanh Navy', selectedSize: 'XL', quantity: 3 }], total: 1470000, status: 'shipped', shippingAddress: { fullName: 'Lê Hoàng C', phone: '0987654321', address: '89 Trần Hưng Đạo, Q.5, TP.HCM' }, paymentMethod: 'momo', createdAt: new Date(Date.now() - 172800000) },
  { id: 'ord-1004', userId: 'usr-4', items: [{ ...PRODUCTS[5], selectedColor: 'Xanh Mint', selectedSize: 'M', quantity: 1 }], total: 270000, status: 'delivered', shippingAddress: { fullName: 'Phạm Văn D', phone: '0933445566', address: '12 Võ Văn Tần, Q.3, TP.HCM' }, paymentMethod: 'cod', createdAt: new Date(Date.now() - 259200000) },
  { id: 'ord-1005', userId: 'usr-5', items: [{ ...PRODUCTS[8], selectedColor: 'Đỏ', selectedSize: 'S', quantity: 2 }], total: 700000, status: 'cancelled', shippingAddress: { fullName: 'Hoàng Thị E', phone: '0977889900', address: '55 Hai Bà Trưng, Q.1, TP.HCM' }, paymentMethod: 'zalopay', createdAt: new Date(Date.now() - 345600000) }
];

export const STATIC_CUSTOMERS = [
  { id: 'usr-1', name: 'Nguyễn Văn A', email: 'nguyenvana@gmail.com', phone: '0901234567', ordersCount: 5, totalSpent: 2500000 },
  { id: 'usr-2', name: 'Trần Thị B', email: 'tranthib@gmail.com', phone: '0912345678', ordersCount: 2, totalSpent: 1200000 },
  { id: 'usr-3', name: 'Lê Hoàng C', email: 'lehoangc@gmail.com', phone: '0987654321', ordersCount: 8, totalSpent: 5400000 },
  { id: 'usr-4', name: 'Phạm Văn D', email: 'phamvand@gmail.com', phone: '0933445566', ordersCount: 1, totalSpent: 270000 },
  { id: 'usr-5', name: 'Hoàng Thị E', email: 'hoangthie@gmail.com', phone: '0977889900', ordersCount: 3, totalSpent: 1800000 }
];

export const STATIC_VOUCHERS: Voucher[] = [
  {
    id: 'vc-1',
    name: 'Giảm giá cuối tuần',
    code: 'WEEKEND20',
    startTime: new Date().toISOString(),
    endTime: new Date(Date.now() + 86400000 * 7).toISOString(),
    type: 'khuyen_mai',
    discountType: 'percent',
    discountValue: 10,
    maxDiscountValue: 50000,
    minOrderValue: 200000,
    maxUsage: 100,
    maxUsagePerUser: 1,
    usedCount: 15,
    isActive: true,
    applicableProducts: ['all']
  },
  {
    id: 'vc-2',
    name: 'Mã giảm giá Khách mới',
    code: 'NEWBIE',
    startTime: new Date(Date.now() - 86400000 * 30).toISOString(),
    endTime: new Date(Date.now() + 86400000 * 30).toISOString(),
    type: 'khuyen_mai',
    discountType: 'fixed',
    discountValue: 20000,
    minOrderValue: 100000,
    maxUsage: 500,
    maxUsagePerUser: 1,
    usedCount: 450,
    isActive: true,
    applicableProducts: ['all']
  }
];
