import { Category, Product, CategoryInfo } from './types';

export const CATEGORY_METADATA: CategoryInfo[] = [
  { 
    name: 'Áo thun nam', 
    slug: 'ao-thun-nam', 
    icon: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=100&h=100&fit=crop' 
  },
  { 
    name: 'Áo thun thể thao nam', 
    slug: 'ao-thun-the-thao-nam', 
    icon: 'https://images.unsplash.com/photo-1581009146145-b5ef03a7401f?w=100&h=100&fit=crop' 
  },
  { 
    name: 'Áo polo nam', 
    slug: 'ao-polo-nam', 
    icon: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=100&h=100&fit=crop' 
  },
  { 
    name: 'Quần thể thao nam', 
    slug: 'quan-the-thao-nam', 
    icon: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=100&h=100&fit=crop' 
  },
  { 
    name: 'Phụ kiện thể thao', 
    slug: 'phu-kien-the-thao', 
    icon: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=100&h=100&fit=crop' 
  },
];

export const CATEGORIES: Category[] = CATEGORY_METADATA.map(c => c.name);

export const PRODUCTS: Product[] = [
  // --- ÁO THUN NAM (8 products) ---
  {
    id: 'at-1',
    slug: 'ao-thun-cotton-starship-premium',
    name: 'Áo Thun Cotton Starship Premium',
    description: 'Chất liệu 100% cotton tự nhiên cao cấp, in logo Starship Entertainment tinh tế. Form dáng hiện đại, thoáng mát.',
    price: 250000,
    category: 'Áo thun nam',
    images: [
      'https://tuanlouis.vn/datafiles/34259/upload/files/%C3%81O%20THUN/IMG_1268.JPG',
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
      'https://images.unsplash.com/photo-1554568218-0f1715e72254?w=800',
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
      'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800'
    ],
    colors: ['Trắng', 'Đen', 'Đỏ', 'Vàng', 'Than', 'Xanh'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 50,
    rating: 4.8,
    reviewsCount: 120,
    features: ['Cotton 100%', 'In logo bền màu', 'Form chuẩn US'],
    isBestSeller: true
  },
  {
    id: 'at-2',
    slug: 'ao-thun-graphic-run-fast',
    name: 'Áo Thun Graphic "Run Fast"',
    description: 'Thiết kế graphic năng động, cá tính. Form áo rộng thoải mái.',
    price: 320000,
    discountPrice: 250000,
    category: 'Áo thun nam',
    images: ['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800'],
    colors: ['Vàng', 'Đen'],
    sizes: ['M', 'L', 'XL'],
    stock: 30,
    rating: 4.5,
    reviewsCount: 45,
    features: ['In lụa cao cấp', 'Cotton 4 chiều', 'Không xù lông'],
    isNew: true
  },
  {
    id: 'at-3',
    slug: 'ao-thun-oversize-urstyle',
    name: 'Áo Thun Oversize UrStyle',
    description: 'Phong cách đường phố hiện đại, form dáng cực chuẩn cho giới trẻ.',
    price: 350000,
    category: 'Áo thun nam',
    images: ['https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800'],
    colors: ['Xanh Rêu', 'Be', 'Đen'],
    sizes: ['M', 'L', 'XL'],
    stock: 40,
    rating: 4.7,
    reviewsCount: 78,
    features: ['Vải dày dặn', 'Form rộng', 'Fashionable']
  },
  {
    id: 'at-4',
    slug: 'ao-thun-henley-co-nut',
    name: 'Áo Thun Henley Cổ Nút',
    description: 'Thiết kế cổ nút tinh tế, mang lại vẻ ngoài lịch lãm nhưng vẫn trẻ trung.',
    price: 380000,
    category: 'Áo thun nam',
    images: ['https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800'],
    colors: ['Xám Ghi', 'Xanh Than'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 25,
    rating: 4.6,
    reviewsCount: 32,
    features: ['Cổ bẻ có nút', 'Vải cotton xốp', 'Dễ phối đồ']
  },
  {
    id: 'at-5',
    slug: 'ao-thun-soc-ngang-urban',
    name: 'Áo Thun Sọc Ngang Urban',
    description: 'Họa tiết sọc ngang kinh điển, trẻ trung và không bao giờ lỗi mốt.',
    price: 290000,
    category: 'Áo thun nam',
    images: ['https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=800'],
    colors: ['Trắng-Xanh', 'Trắng-Đen'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 15,
    rating: 4.4,
    reviewsCount: 28,
    features: ['Sọc dệt trực tiếp', 'Mát tay', 'Vải nhẹ']
  },
  {
    id: 'at-6',
    slug: 'ao-thun-pocket-tee',
    name: 'Áo Thun Pocket Tee',
    description: 'Điểm nhấn túi ngực nhỏ gọn, tinh tế và tiện lợi.',
    price: 270000,
    category: 'Áo thun nam',
    images: ['https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800'],
    colors: ['Hồng Pastel', 'Xanh Mint', 'Trắng'],
    sizes: ['S', 'M', 'L'],
    stock: 20,
    rating: 4.3,
    reviewsCount: 15,
    features: ['Túi ngực thật', 'Vải mềm mịn', 'Kháng khuẩn']
  },
  {
    id: 'at-7',
    slug: 'ao-thun-longline-modern',
    name: 'Áo Thun Longline Modern',
    description: 'Vạt bầu dài thời trang, cực kỳ phù hợp cho phong cách layer.',
    price: 360000,
    category: 'Áo thun nam',
    images: ['https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800'],
    colors: ['Đen', 'Trắng'],
    sizes: ['M', 'L', 'XL'],
    stock: 12,
    rating: 4.9,
    reviewsCount: 64,
    features: ['Vạt bầu dài', 'Cổ tròn rộng', 'Phong cách Layer'],
    isNew: true
  },
  {
    id: 'at-8',
    slug: 'ao-thun-in-chim-stealth',
    name: 'Áo Thun In Chìm Stealth',
    description: 'Logo in chìm tinh tế, chỉ lộ rõ dưới ánh sáng mạnh. Đầy bí ẩn và đẳng cấp.',
    price: 390000,
    category: 'Áo thun nam',
    images: ['https://images.unsplash.com/photo-1554568218-0f1715e72254?w=800'],
    colors: ['Đen Carbon', 'Xám Đậm'],
    sizes: ['M', 'L', 'XL', '2XL'],
    stock: 18,
    rating: 5.0,
    reviewsCount: 10,
    features: ['In phản quang chìm', 'Vải cao cấp', 'Limited Edition']
  },

  // --- ÁO THUN THỂ THAO NAM (8 products) ---
  {
    id: 'att-1',
    slug: 'ao-thun-the-thao-pro-dry',
    name: 'Áo Thun Thể Thao Pro-Dry',
    description: 'Công nghệ thoát ẩm siêu tốc, giữ cơ thể luôn khô thoáng khi tập luyện.',
    price: 350000,
    discountPrice: 280000,
    category: 'Áo thun thể thao nam',
    images: ['https://images.unsplash.com/photo-1581009146145-b5ef03a7401f?w=800'],
    colors: ['Xanh Blue', 'Đen', 'Đỏ'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 100,
    rating: 4.9,
    reviewsCount: 250,
    features: ['Thoát ẩm Pro-Dry', 'Vải siêu nhẹ', 'Co giãn 4 chiều'],
    isBestSeller: true
  },
  {
    id: 'att-2',
    slug: 'ao-tanktop-tap-gym-urarmor',
    name: 'Áo Tanktop Tập Gym UrArmor',
    description: 'Thiết kế khoét sâu nách, giúp tối ưu chuyển động và khoe trọn cơ bắp.',
    price: 290000,
    category: 'Áo thun thể thao nam',
    images: ['https://images.unsplash.com/photo-1541534741688-6078c64b5cc5?w=800'],
    colors: ['Đen', 'Xám', 'Trắng'],
    sizes: ['M', 'L', 'XL'],
    stock: 60,
    rating: 4.7,
    reviewsCount: 110,
    features: ['Khoét sâu nách', 'Vải lưới thoáng khí', 'Nhanh khô']
  },
  {
    id: 'att-3',
    slug: 'ao-compression-dai-tay',
    name: 'Áo Compression Dài Tay',
    description: 'Áo ôm sát cơ thể, hỗ trợ tuần hoàn máu và bảo vệ cơ bắp khi tập nặng.',
    price: 450000,
    category: 'Áo thun thể thao nam',
    images: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800'],
    colors: ['Đen Stealth', 'Xanh Cobalt'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 40,
    rating: 4.8,
    reviewsCount: 95,
    features: ['Công nghệ nén cơ', 'Giữ nhiệt tốt', 'Chống tia UV']
  },
  {
    id: 'att-4',
    slug: 'ao-chay-bo-phan-quang-nightrun',
    name: 'Áo Chạy Bộ Phản Quang NightRun',
    description: 'Trang bị dải phản quang quanh áo, đảm bảo an toàn tuyệt đối khi chạy ban đêm.',
    price: 380000,
    category: 'Áo thun thể thao nam',
    images: ['https://images.unsplash.com/photo-1530143311094-34d807799e8f?w=800'],
    colors: ['Vàng Neon', 'Cam'],
    sizes: ['M', 'L', 'XL'],
    stock: 35,
    rating: 4.6,
    reviewsCount: 50,
    features: ['Phản quang 360 độ', 'Vải mesh siêu thoáng', 'Dễ giặt ủi']
  },
  {
    id: 'att-5',
    slug: 'ao-training-v-neck-sport',
    name: 'Áo Training V-Neck Sport',
    description: 'Thiết kế cổ chữ V trẻ trung, năng động, phù hợp cho mọi bộ môn thể thao.',
    price: 330000,
    category: 'Áo thun thể thao nam',
    images: ['https://images.unsplash.com/photo-1594381898411-846e7d193883?w=800'],
    colors: ['Xanh Mint', 'Trắng', 'Đỏ'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 45,
    rating: 4.5,
    reviewsCount: 40,
    features: ['Cổ V thời trang', 'Kháng khuẩn', 'Không ám mùi'],
    isNew: true
  },
  {
    id: 'att-6',
    slug: 'ao-thun-the-thao-in-hoa-tiet-camo',
    name: 'Áo Thun Thể Thao In Họa Tiết Camo',
    description: 'Họa tiết rằn ri mạnh mẽ, giúp bạn nổi bật trong phòng tập.',
    price: 390000,
    category: 'Áo thun thể thao nam',
    images: ['https://images.unsplash.com/photo-1516726817505-f5ed825624d8?w=800'],
    colors: ['Camo Xám', 'Camo Xanh'],
    sizes: ['M', 'L', 'XL'],
    stock: 28,
    rating: 4.7,
    reviewsCount: 22,
    features: ['In công nghệ 3D', 'Vải Poly-Esther', 'Dày dặn']
  },
  {
    id: 'att-7',
    slug: 'ao-khoac-gio-the-thao-windbreaker',
    name: 'Áo Khoác Gió Thể Thao Windbreaker',
    description: 'Chống gió và mưa nhẹ, lý tưởng cho những buổi tập ngoài trời.',
    price: 650000,
    discountPrice: 550000,
    category: 'Áo thun thể thao nam',
    images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800'],
    colors: ['Đen', 'Xám'],
    sizes: ['M', 'L', 'XL', '2XL'],
    stock: 15,
    rating: 4.9,
    reviewsCount: 35,
    features: ['Chống nước nhẹ', 'Siêu nhẹ bỏ túi', 'Có mũ trùm'],
    isNew: true
  },
  {
    id: 'att-8',
    slug: 'ao-thun-sat-nach-stringer',
    name: 'Áo Thun Sát Nách Stringer',
    description: 'Dành riêng cho các vận động viên thể hình chuyên nghiệp.',
    price: 250000,
    category: 'Áo thun thể thao nam',
    images: ['https://images.unsplash.com/photo-1583454110551-21f2fa2ec617?w=800'],
    colors: ['Vàng Gold', 'Đen', 'Xám'],
    sizes: ['M', 'L', 'XL'],
    stock: 50,
    rating: 4.4,
    reviewsCount: 18,
    features: ['Dây vai mảnh', 'Cotton co giãn', 'Thoáng mát tối đa']
  },

  // --- ÁO POLO NAM (8 products) ---
  {
    id: 'pl-1',
    slug: 'ao-polo-golf-classic-lux',
    name: 'Áo Polo Golf Classic Lux',
    description: 'Form dáng sang trọng, chất liệu vải cá sấu cao cấp mang lại vẻ ngoài đẳng cấp.',
    price: 450000,
    category: 'Áo polo nam',
    images: ['https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=800'],
    colors: ['Trắng', 'Xanh Cyan', 'Đen'],
    sizes: ['M', 'L', 'XL', '2XL'],
    stock: 45,
    rating: 4.9,
    reviewsCount: 150,
    features: ['Vải Pique cao cấp', 'Chống nhăn', 'Cổ áo cứng cáp'],
    isBestSeller: true
  },
  {
    id: 'pl-2',
    slug: 'ao-polo-sporty-mesh',
    name: 'Áo Polo Sporty Mesh',
    description: 'Sự kết hợp giữa thanh lịch của polo và sự năng động của đồ thể thao.',
    price: 420000,
    discountPrice: 380000,
    category: 'Áo polo nam',
    images: ['https://images.unsplash.com/photo-1516257984-b1b4d707412e?w=800'],
    colors: ['Đỏ', 'Trắng', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 30,
    rating: 4.7,
    reviewsCount: 88,
    features: ['Vải thun lạnh', 'Logo thêu tinh xảo', 'Thoáng khí']
  },
  {
    id: 'pl-3',
    slug: 'ao-polo-phoi-bo-tay-stripe',
    name: 'Áo Polo Phối Bo Tay Stripe',
    description: 'Điểm nhấn kẻ sọc ở cổ và tay áo mang lại nét trẻ trung, hiện đại.',
    price: 480000,
    category: 'Áo polo nam',
    images: ['https://images.unsplash.com/photo-1598961942613-28974b399a9a?w=800'],
    colors: ['Be', 'Xanh Than'],
    sizes: ['M', 'L', 'XL'],
    stock: 25,
    rating: 4.6,
    reviewsCount: 42,
    features: ['Bo tay dệt sọc', 'Cotton mịn', 'Form Slim Fit'],
    isNew: true
  },
  {
    id: 'pl-4',
    slug: 'ao-polo-zipper-tech',
    name: 'Áo Polo Zipper Tech',
    description: 'Thay thế nút bấm bằng dây kéo tinh tế, tạo nên phong cách tương lai.',
    price: 520000,
    category: 'Áo polo nam',
    images: ['https://images.unsplash.com/photo-1626497748470-2819d9ca7ba3?w=800'],
    colors: ['Xám Bạc', 'Đen'],
    sizes: ['M', 'L', 'XL'],
    stock: 20,
    rating: 4.8,
    reviewsCount: 30,
    features: ['Khóa kéo kim loại', 'Vải Spandex co giãn', 'Thiết kế Tech-wear']
  },
  {
    id: 'pl-5',
    slug: 'ao-polo-knit-texture',
    name: 'Áo Polo Knit Texture',
    description: 'Vải dệt kim có vân nổi độc đáo, tạo cảm giác dày dặn và sang trọng.',
    price: 550000,
    category: 'Áo polo nam',
    images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800'],
    colors: ['Nâu Đất', 'Xanh Rêu'],
    sizes: ['M', 'L', 'XL'],
    stock: 15,
    rating: 4.5,
    reviewsCount: 20,
    features: ['Dệt kim Texture', 'Giữ form tốt', 'Ấm áp']
  },
  {
    id: 'pl-6',
    slug: 'ao-polo-active-dri-fit',
    name: 'Áo Polo Active Dri-Fit',
    description: 'Dành cho những người yêu thích sự thoải mái tuyệt đối cả ngày dài.',
    price: 390000,
    category: 'Áo polo nam',
    images: ['https://images.unsplash.com/photo-1592303637753-ce1e20d7014e?w=800'],
    colors: ['Xám Khói', 'Xanh Pastel'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 40,
    rating: 4.7,
    reviewsCount: 56,
    features: ['Công nghệ khô nhanh', 'Siêu nhẹ', 'Không cần là ủi']
  },
  {
    id: 'pl-7',
    slug: 'ao-polo-pattern-dot',
    name: 'Áo Polo Pattern Dot',
    description: 'Họa tiết chấm bi nhỏ li ti, tinh tế và lịch sự.',
    price: 490000,
    category: 'Áo polo nam',
    images: ['https://images.unsplash.com/photo-1617415494200-a92da69ceb00?w=800'],
    colors: ['Trắng Chấm Đen', 'Xanh Chấm Trắng'],
    sizes: ['M', 'L', 'XL'],
    stock: 18,
    rating: 4.4,
    reviewsCount: 15,
    features: ['Họa tiết in nhiệt', 'Vải mềm', 'Cổ bẻ thanh lịch']
  },
  {
    id: 'pl-8',
    slug: 'ao-polo-long-sleeve-winter',
    name: 'Áo Polo Long Sleeve Winter',
    description: 'Áo polo tay dài giữ ấm cơ thể trong những ngày se lạnh.',
    price: 580000,
    discountPrice: 450000,
    category: 'Áo polo nam',
    images: ['https://images.unsplash.com/photo-1510214815147-193309a63be3?w=800'],
    colors: ['Đen Carbon', 'Xám Lông Chuột'],
    sizes: ['M', 'L', 'XL', '2XL'],
    stock: 10,
    rating: 4.8,
    reviewsCount: 25,
    features: ['Tay dài cổ bẻ', 'Vải giữ nhiệt', 'Lớp lót mềm'],
    isNew: true
  },

  // --- QUẦN THỂ THAO NAM (8 products) ---
  {
    id: 'qt-1',
    slug: 'quan-short-chay-bo-elite-night',
    name: 'Quần Short Chạy Bộ Elite Night',
    description: 'Siêu nhẹ, có túi khóa kéo an toàn. Đai quần co giãn cực tốt.',
    price: 290000,
    discountPrice: 220000,
    category: 'Quần thể thao nam',
    images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=800'],
    colors: ['Đen', 'Xám'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 60,
    rating: 4.8,
    reviewsCount: 190,
    features: ['Vải dù siêu nhẹ', 'Túi khóa kéo', 'Phản quang'],
    isBestSeller: true
  },
  {
    id: 'qt-2',
    slug: 'quan-jogger-training-urfocus',
    name: 'Quần Jogger Training UrFocus',
    description: 'Thiết kế bo gấu năng động, chất liệu nỉ da cá thoáng mát.',
    price: 450000,
    category: 'Quần thể thao nam',
    images: ['https://images.unsplash.com/photo-1580903211599-fc4f05f4c729?w=800'],
    colors: ['Đen Carbon', 'Xám Ghi'],
    sizes: ['M', 'L', 'XL', '2XL'],
    stock: 45,
    rating: 4.7,
    reviewsCount: 120,
    features: ['Bo gấu thời trang', 'Túi sâu tiện dụng', 'Vải nỉ thoáng'],
    isNew: true
  },
  {
    id: 'qt-3',
    slug: 'quan-dui-tap-gym-2-lop',
    name: 'Quần Đùi Tập Gym 2 Lớp',
    description: 'Tích hợp lớp lót bên trong giúp bảo vệ và hỗ trợ cơ bắp tối ưu.',
    price: 350000,
    category: 'Quần thể thao nam',
    images: ['https://images.unsplash.com/photo-1533107862482-0e6974b06ec4?w=800'],
    colors: ['Đen', 'Xanh'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 35,
    rating: 4.9,
    reviewsCount: 85,
    features: ['Thiết kế 2 lớp', 'Túi đựng điện thoại ẩn', 'Co giãn 4 chiều']
  },
  {
    id: 'qt-4',
    slug: 'quan-long-pants-the-thao-pro',
    name: 'Quần Long Pants Thể Thao Pro',
    description: 'Dáng quần ống suông, phù hợp cho cả tập luyện và dạo phố.',
    price: 490000,
    category: 'Quần thể thao nam',
    images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800'],
    colors: ['Xanh Navy', 'Đen'],
    sizes: ['M', 'L', 'XL'],
    stock: 20,
    rating: 4.6,
    reviewsCount: 40,
    features: ['Ống suông hiện đại', 'Dây rút bền bỉ', 'Không nhăn']
  },
  {
    id: 'qt-5',
    slug: 'quan-short-basketball-legend',
    name: 'Quần Short Basketball Legend',
    description: 'Form rộng rãi, phong cách bóng rổ đường phố Mỹ.',
    price: 320000,
    category: 'Quần thể thao nam',
    images: ['https://images.unsplash.com/photo-1593361131135-26372f6a9e8b?w=800'],
    colors: ['Đỏ Đen', 'Trắng Đen'],
    sizes: ['M', 'L', 'XL', '3XL'],
    stock: 50,
    rating: 4.5,
    reviewsCount: 30,
    features: ['Lưới thoát khí lớn', 'Cạp cao co giãn', 'Form Oversize']
  },
  {
    id: 'qt-6',
    slug: 'quan-legging-tap-gym-nam',
    name: 'Quần Legging Tập Gym Nam',
    description: 'Mặc bên trong quần đùi, giúp giữ nhiệt và bảo vệ đôi chân.',
    price: 280000,
    category: 'Quần thể thao nam',
    images: ['https://images.unsplash.com/photo-1517438984742-1262db08379e?w=800'],
    colors: ['Đen', 'Xám'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 30,
    rating: 4.7,
    reviewsCount: 25,
    features: ['Công nghệ nén cơ', 'Mềm mại', 'Thấm mồ hôi']
  },
  {
    id: 'qt-7',
    slug: 'quan-cargo-sport-da-nang',
    name: 'Quần Cargo Sport Đa Năng',
    description: 'Tích hợp nhiều túi hộp, phong cách quân đội mạnh mẽ.',
    price: 550000,
    category: 'Quần thể thao nam',
    images: ['https://images.unsplash.com/photo-1627282894576-5979c3d4fba7?w=800'],
    colors: ['Xanh Rêu', 'Vàng Cát'],
    sizes: ['M', 'L', 'XL'],
    stock: 12,
    rating: 4.4,
    reviewsCount: 14,
    features: ['Nhiều túi tiện ích', 'Vải kaki co giãn', 'Thời trang bụi bặm'],
    isNew: true
  },
  {
    id: 'qt-8',
    slug: 'quan-short-boi-urbeach',
    name: 'Quần Short Bơi UrBeach',
    description: 'Chất liệu mau khô, họa tiết nhiệt đới rực rỡ.',
    price: 260000,
    category: 'Quần thể thao nam',
    images: ['https://images.unsplash.com/photo-1506630448388-161d02c67623?w=800'],
    colors: ['Họa tiết Summer', 'Xanh Biển'],
    sizes: ['S', 'M', 'L'],
    stock: 100,
    rating: 4.3,
    reviewsCount: 22,
    features: ['Mau khô cực nhanh', 'Lót lưới an toàn', 'In ấn sắc nét']
  },

  // --- PHỤ KIỆN THỂ THAO (8 products) ---
  {
    id: 'pk-1',
    slug: 'binh-nuoc-the-thao-tritan-1l',
    name: 'Bình Nước Thể Thao Tritan 1L',
    description: 'Nhựa cao cấp không chứa BPA, bền chắc và an toàn cho sức khỏe.',
    price: 180000,
    category: 'Phụ kiện thể thao',
    images: ['https://images.unsplash.com/photo-1544200175-ca6e80a7b325?w=800'],
    colors: ['Xanh Trong', 'Đen Khói'],
    sizes: ['1000ml'],
    stock: 200,
    rating: 4.9,
    reviewsCount: 320,
    features: ['Nhựa Tritan BPA Free', 'Có vạch chia dung tích', 'Chống va đập'],
    isBestSeller: true
  },
  {
    id: 'pk-2',
    slug: 'tham-yoga-tpe-8mm-sieu-bam',
    name: 'Thảm Yoga TPE 8mm Siêu Bám',
    description: 'Chống trượt tuyệt đối, độ đàn hồi cực tốt bảo vệ khớp xương.',
    price: 350000,
    category: 'Phụ kiện thể thao',
    images: ['https://images.unsplash.com/photo-1592419044706-39796d40f98c?w=800'],
    colors: ['Tím', 'Xanh Dương'],
    sizes: ['183x61cm'],
    stock: 80,
    rating: 4.8,
    reviewsCount: 150,
    features: ['Vật liệu TPE 2 lớp', 'Chống trượt 2 mặt', 'Dễ vệ sinh'],
    isNew: true
  },
  {
    id: 'pk-3',
    slug: 'tui-the-thao-gym-bag-duffel',
    name: 'Túi Thể Thao Gym Bag Duffel',
    description: 'Ngăn chứa đồ rộng rãi, có ngăn đựng giày riêng biệt cực tiện lợi.',
    price: 450000,
    category: 'Phụ kiện thể thao',
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800'],
    colors: ['Đen Urban', 'Xám Camo'],
    sizes: ['Cỡ Đại'],
    stock: 45,
    rating: 4.7,
    reviewsCount: 95,
    features: ['Ngăn giày riêng', 'Vải chống thấm', 'Quai đeo êm ái']
  },
  {
    id: 'pk-4',
    slug: 'gang-tay-tap-gym-pro-grip',
    name: 'Găng Tay Tập Gym Pro-Grip',
    description: 'Bảo vệ lòng bàn tay khỏi chai sạn, tăng lực bám khi đẩy tạ.',
    price: 150000,
    category: 'Phụ kiện thể thao',
    images: ['https://images.unsplash.com/photo-1583454110551-21f2fa2ec617?w=800'],
    colors: ['Đen Đỏ', 'Full Đen'],
    sizes: ['M', 'L', 'XL'],
    stock: 120,
    rating: 4.6,
    reviewsCount: 210,
    features: ['Lớp đệm lòng bàn tay', 'Khóa dán cổ tay', 'Thoáng khí']
  },
  {
    id: 'pk-5',
    slug: 'non-ket-the-thao-performance',
    name: 'Nón Kết Thể Thao Performance',
    description: 'Chất liệu vải dù cực nhẹ, form nón chuẩn đẹp.',
    price: 220000,
    category: 'Phụ kiện thể thao',
    images: ['https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800'],
    colors: ['Trắng', 'Đen', 'Navy'],
    sizes: ['Free Size'],
    stock: 150,
    rating: 4.5,
    reviewsCount: 65,
    features: ['Lỗ thông gió laser', 'Vải dù nhanh khô', 'Khóa gài điều chỉnh']
  },
  {
    id: 'pk-6',
    slug: 'day-nhay-the-luc-speed-rope',
    name: 'Dây Nhảy Thể Lực Speed Rope',
    description: 'Thiết kế khí động học cho tốc độ xoay cực cao.',
    price: 120000,
    category: 'Phụ kiện thể thao',
    images: ['https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=800'],
    colors: ['Đen Red'],
    sizes: ['3m'],
    stock: 100,
    rating: 4.8,
    reviewsCount: 40,
    features: ['Vòng bi xoay 360', 'Dây thép bọc nhựa', 'Chỉnh được độ dài']
  },
  {
    id: 'pk-7',
    slug: 'tat-the-thao-cotton-cushioned',
    name: 'Tất Thể Thao Cotton Cushioned',
    description: 'Lớp đệm dày ở gót và mũi chân giúp giảm chấn thương.',
    price: 45000,
    category: 'Phụ kiện thể thao',
    images: ['https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=800'],
    colors: ['Trắng', 'Đen'],
    sizes: ['Standard'],
    stock: 500,
    rating: 4.7,
    reviewsCount: 180,
    features: ['Cotton 80%', 'Đệm lòng bàn chân', 'Vùng nén vòm chân']
  },
  {
    id: 'pk-8',
    slug: 'bo-5-day-mini-band-khang-luc',
    name: 'Bộ 5 Dây Mini Band Kháng Lực',
    description: 'Hỗ trợ tập luyện mông và chân hiệu quả tại nhà.',
    price: 150000,
    category: 'Phụ kiện thể thao',
    images: ['https://images.unsplash.com/photo-1518459031867-a89b944bffe4?w=800'],
    colors: ['Multicolor'],
    sizes: ['Set 5'],
    stock: 120,
    rating: 4.9,
    reviewsCount: 55,
    features: ['Cao su tự nhiên', '5 mức kháng lực', 'Tặng kèm túi đựng']
  }
];
